wundergraph/cosmo

router/cmd/custom/module/module.go
router/core/modules.go
router/core/transport.go

feat: simplify OnOriginResponse hook

---

studio/src/pages/[organizationSlug]/graph/[slug]/changelog.tsx

fix: changelog date overflow

---

cli/package.json
cli/src/commands/federated-graph/index.ts
cli/src/commands/index.ts
cli/src/commands/router/commands/compose.ts
cli/src/commands/router/commands/fetch.ts
cli/src/commands/router/index.ts
cli/src/commands/subgraph/commands/introspect.ts
cli/src/utils.ts
pnpm-lock.yaml

feat: router compose command

---

router/go.mod
router/go.sum

fix: update engine to support schema extension without body

---

composition/src/utils/constants.ts
composition/tests/utils/utils.ts

chore: fix composition link directive definition

---

studio/src/components/federatedgraphs-cards.tsx

fix: router docs dialog

---

demo/employees/go.mod
demo/employees/go.sum
demo/employees/main.go
demo/employees/subgraph/employees.go
demo/employees/subgraph/entity.resolvers.go
demo/employees/subgraph/schema.resolvers.go
demo/family/go.mod
demo/family/go.sum
demo/family/main.go
demo/family/subgraph/employees.go
demo/family/subgraph/entity.resolvers.go
demo/hobbies/go.mod
demo/hobbies/go.sum
demo/hobbies/main.go
demo/hobbies/subgraph/employees.go
demo/hobbies/subgraph/entity.resolvers.go
demo/products/go.mod
demo/products/go.sum
demo/products/main.go
demo/products/subgraph/entity.resolvers.go

fix(demo): add cors headers

---

controlplane/src/core/services/ApolloMigrator.ts

fix: labels of the migrated graphs

---

controlplane/src/core/auth-utils.ts
controlplane/src/core/controllers/auth.ts
controlplane/src/core/errors/errors.ts

fix: avoid excessive error logs in session handler

---

controlplane/src/core/auth-utils.ts
controlplane/src/core/repositories/SubgraphRepository.ts
otelcollector/otel-config.yaml

fix: reduce error logs

---

controlplane/src/core/services/ApiKeyAuthenticator.ts

fix: api key last used update

---

router/internal/metric/agent.go
router/internal/trace/agent.go

feat: enable client compression for metrics and traces

---

controlplane/src/core/controllers/auth.ts

Another round to prevent logging authentication issues as error logs. Important for monitoring.

feat: only log system errors as errors

---

router/go.mod
router/go.sum

fix: address __typename and fragment engine issues

---

composition/src/errors/errors.ts
composition/src/normalization/utils.ts
composition/tests/federation-factory.test.ts
composition/tests/fieldset.test.ts

fix: consider nested entity keys to be shareable

---

router/cmd/main.go
router/core/router.go
router/core/transport.go
router/internal/config/config.go

feat: make request timeout configurable

---

studio/src/components/app-provider.tsx

fix: only redirect to login when user is actually logged out

---

router/core/router.go

fix: don't poll when static router config is provided

---

composition/src/federation/federation-factory.ts
composition/tests/arguments.test.ts

feat: account for extension field arguments

---

composition/src/federation/federation-factory.ts
router/go.mod
router/go.sum

fix: composition false flag

---

router/go.mod
router/go.sum

chore: update engine (inline fragment fix)

---

cli/src/commands/auth/utils.ts
cli/src/core/config.ts
docker/keycloak/realm.json
helm/cosmo/charts/keycloak/templates/realm-config-map.yml

fix: update realm json and modify config

---

keycloak/theme/src/main/resources/theme/cosmo/login/login-idp-link-confirm.ftl
keycloak/theme/src/main/resources/theme/cosmo/login/login-oauth-grant.ftl
keycloak/theme/src/main/resources/theme/cosmo/login/login-reset-password.ftl
keycloak/theme/src/main/resources/theme/cosmo/login/messages/messages_en.properties
keycloak/theme/src/main/resources/theme/cosmo/login/resources/scss/login.scss

fix: ui of a few keycloak screens

---

connect/src/wg/cosmo/platform/v1/platform_pb.ts
controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/repositories/FederatedGraphRepository.ts
controlplane/src/types/index.ts
proto/wg/cosmo/platform/v1/platform.proto
studio/src/pages/[organizationSlug]/graph/[slug]/changelog.tsx

We simply fetch more items on end of page scroll

feat: changelog pagination

---

cli/src/commands/auth/commands/login.ts
cli/src/commands/auth/commands/logout.ts
cli/src/commands/auth/index.ts
cli/src/commands/auth/user-config.ts
cli/src/commands/index.ts
cli/src/utils.ts

feat: add logout command

---

controlplane/src/core/repositories/analytics/MetricsDashboardRepository.ts

fix: range in error query

---

router/go.mod
router/go.sum

fix: update engine to address representation issues

---

studio/src/components/app-provider.tsx

fix: fixed issue where expired session would cause redirect loop

---

controlplane/src/core/bufservices/PlatformService.ts

fix: remove member

---

studio/src/components/analytics/data-table.tsx
studio/src/components/analytics/getColumnData.tsx
studio/src/components/ui/dialog.tsx
studio/src/components/ui/dialog2.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/changelog.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/checks.tsx

fix: click on analaytics row menu opens trace view

---

controlplane/src/core/repositories/analytics/MetricsDashboardRepository.ts
studio/src/components/analytics/delta-badge.tsx
studio/src/components/analytics/toolbar.tsx
studio/src/components/info-tooltip.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/analytics/index.tsx

feat: add 1 and 4 hour ranges, refresh button and minor improvements

---

router/go.mod
router/go.sum

fix: update engine to address entity array issues

---

studio/src/components/analytics/trace.tsx

fix: fixed issue where tracing elements would render on top of the page header

---

router/core/router.go

fix: track graphql errors in metrics

---

router/core/graphql_handler.go
router/core/graphql_prehandler.go
router/core/router.go
router/internal/metric/handler.go
router/internal/metric/store.go

fix: collect request metrics as early as possible

---

router/core/graphql_prehandler.go

fix: store operation Hash and Name correctly

---

router/core/graphql_prehandler.go

fix: add operation attrs to request latency metric

---

controlplane/package.json
pnpm-lock.yaml
shared/package.json
studio/package.json
studio/src/components/app-provider.tsx
studio/src/components/federatedgraphs-cards.tsx
studio/src/components/layout/dashboard-layout.tsx
studio/src/components/layout/graph-layout.tsx
studio/src/components/layout/nav.tsx
studio/src/components/layout/title-layout.tsx
studio/src/components/user-menu.tsx
studio/src/pages/[organizationSlug]/apikeys.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/changelog.tsx
studio/src/pages/[organizationSlug]/graphs.tsx
studio/src/pages/[organizationSlug]/members.tsx
studio/src/pages/[organizationSlug]/settings.tsx
studio/src/pages/[organizationSlug]/subgraphs.tsx
studio/src/pages/[organizationSlug]/webhooks.tsx

fix: flickering issue on change of orgs

---

cli/src/commands/router/commands/token/commands/create.ts
cli/src/commands/router/commands/token/commands/delete.ts
scripts/create-cli-demo.sh
scripts/create-local-demo.sh

fix: update local demo script and fix the create router token cmd

---

controlplane/clickhouse/migrations/20230927211049_operation_requests_metrics_mv.sql
controlplane/clickhouse/migrations/20230928074635_operation_latency_metrics_mv.sql
router/internal/metric/store.go

feat: version metric meter

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/workflows/close-stale.yml
.github/workflows/create-issue.yml

chore: add bug template

---

connect/src/wg/cosmo/platform/v1/platform-PlatformService_connectquery.ts
connect/src/wg/cosmo/platform/v1/platform_connect.ts
connect/src/wg/cosmo/platform/v1/platform_pb.ts
controlplane/src/core/bufservices/PlatformService.ts
pnpm-lock.yaml
proto/wg/cosmo/platform/v1/platform.proto
studio/package.json
studio/src/components/layout/layout.tsx
studio/src/components/layout/nav.tsx
studio/src/components/layout/title-layout.tsx
studio/src/components/ui/alert-dialog.tsx
studio/src/pages/[organizationSlug]/apikeys.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/checks/[checkID].tsx
studio/src/pages/[organizationSlug]/graph/[slug]/checks/index.tsx
studio/src/pages/[organizationSlug]/members.tsx
studio/src/pages/[organizationSlug]/settings.tsx

Fixes ENG-4271 - Jumpy Layout
Fixes ENG-4212 - Organization Page Redesign
Fixes ENG-4256 - Force check confirmation dialog
Fixes logo link
Fixes some ui spacing

fix: ui improvements

---

router/core/graphql_prehandler.go

feat: add graphql client info to metric attributes

---

router-tests/integration_test.go
router/core/graphql_handler.go

Adds tests for Operations with variables. Fixes variables usage.

fix: usage of variables

---

controlplane/src/core/repositories/FederatedGraphRepository.ts
controlplane/src/core/repositories/SubgraphRepository.ts

fix(controlplane): check array length

---

router/internal/trace/utils.go

chore: ignore websocket requests from traces

---

studio/src/pages/[organizationSlug]/graph/[slug]/analytics/index.tsx

fix: always show top 5 in metrics overview

---

router/internal/graphqlmetrics/aggregation.go
router/internal/graphqlmetrics/aggregation_test.go
router/internal/graphqlmetrics/exporter_test.go

fix: consider request info when aggregating metrics

---

.github/workflows/router-ci.yaml
demo/pkg/subgraphs/employees/subgraph/entity.resolvers.go
demo/pkg/subgraphs/employees/subgraph/schema.resolvers.go
demo/pkg/subgraphs/family/subgraph/entity.resolvers.go
demo/pkg/subgraphs/products/subgraph/entity.resolvers.go

fix: fix team_mates demo resolver

---

Makefile
docker-compose.full.yml

chore(demo): fix full demo

---

controlplane/src/core/composition/schemaCheck.ts

fix: don't consider dangerous change as breaking

---

controlplane/src/core/bufservices/PlatformService.ts

feat: use ch query cache for point query

---

graphqlmetrics/cmd/main.go
graphqlmetrics/config/config.go

feat: provide debug mode in gql collector

---

README.md

chore: update README to specify docker compose version

---

connect/src/wg/cosmo/platform/v1/platform_pb.ts
controlplane/src/core/bufservices/PlatformService.ts
proto/wg/cosmo/platform/v1/platform.proto
studio/src/pages/[organizationSlug]/settings.tsx

fix: minor issues of sso

---

studio/src/pages/[organizationSlug]/settings.tsx

fix: links and ui

---

.github/workflows/helm-ci.yaml
Makefile
helm/Makefile
helm/README.md
helm/cosmo/CHART.md
helm/cosmo/Chart.yaml
helm/cosmo/README.md
helm/cosmo/charts/clickhouse/CHART.md
helm/cosmo/charts/clickhouse/Chart.yaml
helm/cosmo/charts/controlplane/CHART.md
helm/cosmo/charts/graphqlmetrics/CHART.md
helm/cosmo/charts/keycloak/CHART.md
helm/cosmo/charts/keycloak/Chart.yaml
helm/cosmo/charts/otelcollector/CHART.md
helm/cosmo/charts/otelcollector/Chart.yaml
helm/cosmo/charts/router/CHART.md
helm/cosmo/charts/router/Chart.yaml
helm/cosmo/charts/studio/CHART.md
helm/cosmo/charts/studio/Chart.yaml

Example: https://github.com/wundergraph/cosmo/blob/dustin/autogenerate-helm-docs/helm/cosmo/CHART.md

chore: generate docs for helm charts

---

studio/src/components/layout/auth-layout.tsx
studio/src/pages/login.tsx
studio/src/pages/signup.tsx

fix: minor ui improvements

---

studio/src/components/ui/button.tsx

fix: link button styles in safari

---

keycloak/theme/src/main/resources/theme/cosmo/login/login-idp-link-email.ftl
keycloak/theme/src/main/resources/theme/cosmo/login/resources/scss/login.scss

fix: improve idp email styling

---

helm/cosmo/charts/studio/templates/deployment.yaml

fix(helm): use correct value for slack client id

---

helm/cosmo/CHART.md
helm/cosmo/values.full.yaml
helm/cosmo/values.yaml

feat(helm): use internal dns for keycloak

---

cdn-server/cdn/package.json
cdn-server/package.json

fix: declare cosmo-cdn package as public

---

router/core/operation_parser.go
router/internal/cdn/cdn.go

chore: fix typo in function name (cosmetic only)

---

studio/src/pages/[organizationSlug]/graph/[slug]/clients.tsx

fix: use graph routing url in snippets

---

studio/src/components/layout/dashboard-layout.tsx

fix: star banner on big screens

---

cli/src/commands/router/index.ts

fix: do not require login for download-binary

---

router-tests/go.mod
router-tests/go.sum
router-tests/integration_test.go
router-tests/testdata/tracing.json
router/go.mod
router/go.sum

chore: update graphql-go-tools dependency

---

cli/src/commands/router/commands/download-binary.ts

chore: add explicit router version to download-binary output

---

controlplane/migrations/0067_third_multiple_man.sql
controlplane/migrations/meta/0067_snapshot.json
controlplane/migrations/meta/_journal.json
controlplane/src/core/services/Authorization.ts
controlplane/src/db/schema.ts

fix: api key resource deletion on delete of target

---

studio/src/components/app-provider.tsx

The last used organization slug is now stored in a cookie so you will always be redirect to the last used organization after coming back to cosmo studio or after logging in again.

feat: remember and redirect to last used organisation

---

studio/src/pages/[organizationSlug]/settings.tsx

fix: update link to docs for graph access control

---

helm/README.md
helm/cosmo/README.md
helm/cosmo/charts/cdn/CHART.md
helm/cosmo/charts/cdn/values.yaml
helm/cosmo/charts/controlplane/CHART.md
helm/cosmo/charts/controlplane/values.yaml
helm/cosmo/charts/graphqlmetrics/CHART.md
helm/cosmo/charts/graphqlmetrics/values.yaml
helm/cosmo/charts/router/CHART.md
helm/cosmo/charts/router/templates/config-map.yaml
helm/cosmo/charts/router/templates/deployment.yaml
helm/cosmo/charts/router/values.yaml
helm/cosmo/charts/studio/CHART.md
helm/cosmo/charts/studio/values.yaml
helm/cosmo/values.full.yaml

- Avoid chart depedencies
- Point to correct graphqlmetrics collector URL
- Allow to pass custom environment variables

feat: improve router helm chart

---

studio/src/components/layout/graph-layout.tsx

fix: minor ui fixes

---

studio/src/components/composition-errors-banner.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/changelog/index.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/schema/sdl.tsx

fix: changelog page

---

README.md
controlplane/src/core/bufservices/PlatformService.ts
docker-compose.full.yml
studio/src/pages/[organizationSlug]/graph/[slug]/clients.tsx

This PR makes persistent operations working with the full demo of the repository. Additionally, `--json` does not work with all curl clients. I refactored to use classic headers. Therefore, we forgot to await the upload procedure in the controlplane which swallowed upload errors.

fix: po demo, await po upload

---

router/core/router.go

fix: shutdown prom server on exit

---

controlplane/src/bin/seed-billing.ts

fix: make description optionally

---

controlplane/src/bin/billing.json
controlplane/src/bin/seed-billing.ts

fix: avoid -1 in limits, ensure always limits

---

controlplane/migrations/0070_glorious_skaar.sql
controlplane/migrations/0070_mute_silver_fox.sql
controlplane/migrations/meta/0070_snapshot.json
controlplane/migrations/meta/_journal.json
controlplane/src/db/schema.ts
studio/src/pages/[organizationSlug]/usages.tsx

feat: remove deprecated columns

---

studio/src/pages/[organizationSlug]/apikeys.tsx

fix: api keys creation when rbac is off

---

controlplane/src/core/services/Keycloak.ts

fix: invite user

---

studio/src/components/discussions/discussions.tsx
studio/src/components/discussions/schemas.tsx
studio/src/components/schema/sdl-viewer.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/discussions/[discussionId].tsx
studio/src/pages/[organizationSlug]/subgraph/[subgraphSlug]/discussions/[discussionId].tsx

fix: discussion link and defaults

---

cdn-server/src/s3.ts
router/internal/controlplane/configpoller/config_poller.go

fix(cdn): return 404 when config does not exist

---

cdn-server/cdn/src/index.ts
cdn-server/src/s3.ts

fix: pass context for r2

---

router/internal/controlplane/configpoller/config_poller.go

chore: return proper error on config fetch

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/repositories/BillingRepository.ts
controlplane/src/core/services/BillingService.ts

fix: delete organization

---

controlplane/src/core/services/ApolloMigrator.ts

fix: apollo migration

---

router/cmd/instance.go
router/config.yaml
router/config/config.go
router/core/router.go
router/go.mod
router/go.sum
router/internal/handler/cors/cors.go
router/internal/trace/config.go
router/internal/trace/meter.go
router/internal/trace/propagation.go
studio/src/lib/insights-helpers.ts

```yaml
telemetry:
tracing:
propagation:
trace_context: true
baggage: false
jaeger: false
b3: false
```

feat: support custom trace propagation

---

studio/src/components/date-picker-with-range.tsx

fix: revert start of day on date picker

---

pnpm-lock.yaml
studio/package.json
studio/src/components/analytics/data-table.tsx
studio/src/components/analytics/field-usage.tsx
studio/src/components/checks/changes-table.tsx
studio/src/components/layout/graph-layout.tsx
studio/src/components/layout/subgraph-layout.tsx
studio/src/components/schema/sdl-viewer.tsx
studio/src/components/subgraphs-table.tsx
studio/src/components/ui/table.tsx
studio/src/lib/schema-helpers.ts
studio/src/pages/[organizationSlug]/apikeys.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/checks/index.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/clients.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/compositions/[compositionId]/index.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/compositions/index.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/schema/index.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/schema/sdl.tsx
studio/src/pages/[organizationSlug]/integrations.tsx
studio/src/pages/[organizationSlug]/subgraph/[subgraphSlug]/graphs.tsx
studio/src/pages/[organizationSlug]/subgraph/[subgraphSlug]/index.tsx
studio/src/pages/[organizationSlug]/subgraph/[subgraphSlug]/schema.tsx
studio/src/pages/[organizationSlug]/webhooks.tsx

Fixes ENG-4749
Fixes ENG-4752
Fixes ENG-4751

fix: schema performance, composition crash and minor ui

---

studio/src/components/audit-log-table.tsx
studio/src/pages/[organizationSlug]/audit-log.tsx

fix: empty screen audit logs

---

router/core/router.go
router/internal/trace/middleware.go
router/internal/trace/transport.go
router/internal/trace/utils.go

fix: skip healthchecks requests for tracing

---

controlplane/src/core/repositories/analytics/AnalyticsRequestViewRepository.ts
controlplane/src/core/repositories/analytics/MetricsRepository.ts
controlplane/src/core/repositories/analytics/util.ts
studio/src/components/audit-log-table.tsx
studio/src/pages/[organizationSlug]/audit-log.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/analytics/index.tsx
studio/src/pages/[organizationSlug]/graph/[slug]/analytics/traces.tsx

fix: date and range filter for traces

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/db/models.ts
studio/src/pages/[organizationSlug]/settings.tsx

fix: allow the member of the org to leave

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/db/models.ts

fix: organization_invitation.deleted event and set auditableType

---

controlplane/src/core/bufservices/PlatformService.ts
studio/src/pages/[organizationSlug]/graph/[slug]/index.tsx

fix: refresh button in the overview page

---

router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

chore: update engine version

---

cli/src/commands/subgraph/commands/move.ts

fix: remove typo in move option

---

controlplane/migrations/0078_busy_jasper_sitwell.sql
controlplane/migrations/meta/0078_snapshot.json
controlplane/migrations/meta/_journal.json
controlplane/src/db/schema.ts

fix: allow to create subgraph and federated graphs with same name

---

studio/src/components/checks/changes-table.tsx
studio/src/components/playground/view-headers.tsx
studio/src/components/ui/select.tsx
studio/src/pages/[organizationSlug]/[namespace]/subgraph/[subgraphSlug]/discussions/[discussionId].tsx

fix: broken links and ui overflows

---

router/core/router.go
router/pkg/otel/attributes.go

feat: add federated graph id to attributes

---

studio/src/components/dashboard/NamespaceSelector.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/index.tsx

fix:  namespace selector list on org change

---

cli/src/commands/federated-graph/commands/create.ts
cli/src/commands/subgraph/commands/create.ts
controlplane/src/core/bufservices/PlatformService.ts

fix: validate routing urls

---

controlplane/package.json
pnpm-lock.yaml

fix(deps): upgrade bullmq

---

.github/ISSUE_TEMPLATE/bug_report.yaml

chore: update github bug template

---

controlplane/src/core/webhooks/OrganizationWebhookService.ts

fix: slack notification link

---

controlplane/src/bin/db-migrate.ts
controlplane/src/core/migrate.ts
controlplane/src/core/plugins/database.ts

fix: support tls when migrate

---

cli/src/commands/federated-graph/commands/check.ts
cli/src/commands/federated-graph/commands/create.ts
cli/src/commands/federated-graph/commands/list.ts
cli/src/commands/federated-graph/commands/update.ts
cli/src/commands/subgraph/commands/check.ts
cli/src/commands/subgraph/commands/delete.ts
cli/src/commands/subgraph/commands/list.ts
cli/src/commands/subgraph/commands/publish.ts
cli/src/commands/subgraph/commands/update.ts

fix: cli tables ui

---

controlplane/src/core/bufservices/PlatformService.ts
studio/src/components/subgraphs-table.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/checks/[checkId]/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/subgraph/[subgraphSlug]/index.tsx

fix: missing namespace for platform operations

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/index.tsx

fix: view usage button style alignment

---

controlplane/clickhouse/migrations/20230825095359_traces_mv.sql
controlplane/clickhouse/migrations/20230910193138_traces_by_operation_quarter_hourly_mv.sql
controlplane/clickhouse/migrations/20230910200148_traces_by_client_quarter_hourly_mv.sql
controlplane/clickhouse/migrations/20230910201357_traces_by_http_status_code_quarter_hourly_mv.sql
router/core/router.go
router/pkg/trace/middleware.go
router/pkg/trace/middleware_test.go

refactor(traces): improve root span instrumentation

---

controlplane/src/core/bufservices/PlatformService.ts

fix: audit log for subgraph member addition and removal

---

README.md
cdn-server/Dockerfile
controlplane/Dockerfile
controlplane/vite.config.ts
package.json
studio/Dockerfile

https://nodejs.org/en/about/previous-releases

feat: upgrade to active lts node images

---

.github/actions/go/action.yaml
.github/actions/node/action.yaml
.github/workflows/aws-lambda-router-ci.yaml
.github/workflows/aws-router-binary-release.yaml
.github/workflows/cdn-ci.yaml
.github/workflows/cli-ci.yaml
.github/workflows/composition-ci.yaml
.github/workflows/controlplane-ci.yaml
.github/workflows/graphqlmetrics-ci.yaml
.github/workflows/helm-ci.yaml
.github/workflows/helm-deployment.yaml
.github/workflows/image-release.yml
.github/workflows/images-ci.yaml
.github/workflows/labeler.yaml
.github/workflows/pr-title.yaml
.github/workflows/release-preview.yaml
.github/workflows/release.yaml
.github/workflows/router-binary-release.yaml
.github/workflows/router-ci.yaml
.github/workflows/shared-ci.yaml
.github/workflows/studio-ci.yaml

Remove Node.js deprecations in CI

chore: upgrade ci workflows actions

---

.github/labeler.yml
.github/workflows/labeler.yaml
helm/cosmo/charts/otelcollector/CHART.md
helm/cosmo/charts/otelcollector/templates/deployment.yaml
helm/cosmo/charts/otelcollector/values.yaml
helm/cosmo/charts/router/CHART.md
helm/cosmo/charts/router/values.yaml

chore: unify custom config in helm charts

---

controlplane/drizzle.config.ts
controlplane/package.json
controlplane/src/core/repositories/analytics/AnalyticsDashboardViewRepository.ts
controlplane/src/core/repositories/analytics/MetricsRepository.ts
controlplane/src/core/repositories/analytics/SubgraphMetricsRepository.ts
pnpm-lock.yaml

fix: prepend ch queries correctly with database name

---

helm/cosmo/charts/cdn/templates/secret.yaml
helm/cosmo/charts/controlplane/templates/secret.yaml
helm/cosmo/charts/graphqlmetrics/templates/secret.yaml
helm/cosmo/charts/otelcollector/templates/secret.yaml
helm/cosmo/charts/router/templates/secret.yaml

Fix secreat creation, create secret if existingSecret is not defined.

fix(helm): optional secret creation

---

studio/src/components/federatedgraphs-cards.tsx

chore: ensure image is always pulled in examples

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/routers.tsx

fix: link to composition from routers page

---

router/internal/controlplane/configpoller/config_poller.go

fix: don't panic when config is nil

---

controlplane/src/core/bufservices/PlatformService.ts

fix: check for config version id when fetching router composition

---

.github/workflows/controlplane-ci.yaml
.github/workflows/image-release.yml
.github/workflows/images-ci.yaml
.github/workflows/router-ci.yaml

chore: use private docker credentials

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/util.ts
controlplane/test/utils.test.ts
controlplane/vite.config.ts

fix: label matcher validation

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/routers.tsx

fix: show loader on routers page

---

router/pkg/config/config.go
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/analytics/[traceID].tsx

fix: disable variable export by default

---

controlplane/src/core/repositories/SchemaCheckRepository.ts

fix: import

---

controlplane/src/core/repositories/analytics/RouterMetricsRepository.ts

fix: remove duplicated columns

---

helm/cosmo/charts/graphqlmetrics/CHART.md
helm/cosmo/charts/graphqlmetrics/values.yaml
helm/cosmo/charts/otelcollector/CHART.md
helm/cosmo/charts/otelcollector/values.yaml
helm/cosmo/charts/router/CHART.md
helm/cosmo/charts/router/values.yaml
otelcollector/otel-config.yaml
otelcollector/otelcol-builder.yaml

Remove memory_limiter as suggested here https://github.com/open-telemetry/opentelemetry-collector/issues/8343 and encourage it in all Cosmo Go applications.

feat: recommend GOMEMLIMIT and remove memory limiter

---

router/pkg/config/__snapshots__/config_test.snap
router/pkg/config/config.go

fix: router listen address default port

---

controlplane/src/core/webhooks/OrganizationWebhookService.ts
studio/src/components/subgraphs-table.tsx

We have a dedicated page for all changelogs for a schema version. We link to that.

fix: link to changelog in slack update

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/images-ci.yaml
.github/workflows/router-ci.yaml
CONTRIBUTING.md

chore: make ci working for forks

---

studio/src/components/subgraphs-table.tsx

fix: view button in subgraph table

---

cli/package.json
cli/src/commands/auth/commands/whoami.ts
cli/src/index.ts
pnpm-lock.yaml

Gracefully catch exceptions and provide a tip to solve it.

feat: handle exceptions gracefully

---

demo/update_token.sh
router-tests/modules/module_test.go
scripts/create-full-local-demo.sh
scripts/delete-full-local-demo.sh

chore: full cosmo demo, multiple envs

---

studio/src/components/analytics/trace-details.tsx
studio/src/lib/schema-helpers.ts
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/analytics/traces.tsx

Also refactors components around and removes a redundant traceID page.

feat: default vars for run query in trace page

---

.github/ISSUE_TEMPLATE/bug_report.yaml

chore: update bug_report.yaml

---

router-tests/go.mod
router-tests/go.sum
router/Makefile
router/go.mod
router/go.sum

- fix composite key with nested objects planning
- fix planning nested requests of fields selection of interface
- add support of key resolvable: false

chore: update engine

---

studio/src/components/analytics/metrics.tsx

fix: maintain consistent links

---

router/core/graphql_prehandler.go

fix: don't log unexpected EOF client issues as errors

---

studio/src/components/app-provider.tsx
studio/src/components/user-menu.tsx
studio/src/pages/_document.tsx

Identifies users on Koala.
Completes ENG-4941

chore: koala identify call

---

router/pkg/config/config.schema.json
router/pkg/config/config_test.go
router/pkg/config/fixtures/regex-decoding.yaml
router/pkg/config/fixtures/regex-empty-decoding.yaml
router/pkg/config/marshaler.go
router/pkg/config/testdata/config_full.json

fix(router): decode empty array of Regex in config

---

admission-server/package.json
admission-server/src/index.ts
controlplane/src/core/composition/composer.ts
controlplane/src/core/services/AdmissionWebhookController.ts
pnpm-lock.yaml

feat: improve admission controller

---

controlplane/src/core/bufservices/PlatformService.ts
studio/src/pages/[organizationSlug]/settings.tsx

fix: improve ui and logs

---

studio/next.config.mjs

Test [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) configuration without blocking content.

feat: configure CSP for studio

---

studio/next.config.mjs

chore(studio): enable CSP in production

---

studio/next.config.mjs

fix: soften CSP on playground page

---

cli/src/core/config.ts

feat: show warning when both auth methods are used

---

cdn-server/src/index.ts

fix(cdn): shutdown gracefully

---

controlplane/src/core/bufservices/PlatformService.ts

Due to GitHub api error, linting issues and the final result of checks were not being updated.

fix: github check api crashes schema check

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/playground.tsx
studio/src/pages/[organizationSlug]/settings.tsx
studio/src/styles/playground.css

- This shows the navbar in the playground.
- Fixes OIDC settings not refreshing on org change
Fixes ENG-4979

fix: missing navbar in playground and settings page refresh

---

docker-compose.full.yml

chore: remove AMD arch selection from docker compose

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/util.ts
docker-compose.full.yml
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/index.tsx
studio/src/pages/[organizationSlug]/graphs.tsx

We create subgraph name with the same name for the monograph. This may have conflicts. We gracefully handle this and communicate to the user

fix: conflicting subgraph name on monograph creation

---

controlplane/package.json
controlplane/src/core/repositories/OrganizationRepository.ts
controlplane/test/integrations.test.ts
controlplane/test/test-util.ts
pnpm-lock.yaml

Webhooks and slack were not firing because incorrect ids were being returned

fix: webhook and slack retrieving incorrect graph list

---

studio/src/components/schema/sdl-viewer.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/compositions/[compositionId]/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/sdl.tsx
studio/src/pages/[organizationSlug]/[namespace]/subgraph/[subgraphSlug]/schema.tsx

fix: make the downloaded file name the same as the target name

---

controlplane/src/core/services/ApolloMigrator.ts

fix: improve error handling in the migrator

---

studio/src/components/dashboard/NamespaceSelector.tsx
studio/src/components/federatedgraphs-cards.tsx
studio/src/pages/[organizationSlug]/graphs.tsx
studio/src/pages/[organizationSlug]/lint-policy.tsx
studio/src/pages/[organizationSlug]/subgraphs.tsx

fix: remove namespace from local storage

---

cli/src/commands/auth/utils.ts

fix: don't enforce org slug when using API key

---

Makefile
pnpm-lock.yaml
studio/package.json
studio/src/components/app-provider.tsx
studio/src/hooks/use-cookie-organization.ts

fix: stringify org cookie before comparison

---

helm/cosmo/Chart.yaml
helm/cosmo/README.md
helm/cosmo/charts/controlplane/templates/organization-seed.yaml

fix: pass database certs when seeding

---

controlplane/src/bin/seed.ts
controlplane/src/core/test-util.ts
controlplane/test/test-util.ts

feat: support TLS in organization seed

---

studio/src/pages/[organizationSlug]/apikeys.tsx

fix: everyone with write access can create api keys

---

Makefile
otelcollector/Dockerfile
otelcollector/otel-config.yaml
otelcollector/otelcol-builder.yaml

feat: upgrade otelcollector to 0.98.0

---

.github/workflows/router-ci.yaml
docker-compose.yml
docker/redis/redis.conf

chore: fix local redis tests

---

.github/workflows/pr-title.yaml

https://github.blog/2023-08-09-four-tips-to-keep-your-github-actions-workflows-secure/

chore: hardening workflow scripts

---

demo/cmd/employees/main.go
router/internal/retrytransport/retry_transport.go
router/internal/retrytransport/retry_transport_test.go

fix: retry on 500 origin errors

---

router-tests/websocket_test.go
router/core/factoryresolver.go

fix: set default ws subscription subprotocol

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/controllers/scim.ts
controlplane/src/core/repositories/UserRepository.ts

fix: verify the user from keycloak and sanitize emails

---

controlplane/src/core/bufservices/PlatformService.ts

Remove write access check for reading overrides

fix: write access for operation overrides

---

pnpm-lock.yaml
studio/src/components/schema/sdl-viewer-monaco.tsx
studio/src/hooks/use-hash.ts
studio/src/lib/schema-helpers.ts
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/checks/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/compositions/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/overrides.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/sdl.tsx
studio/src/styles/globals.css

- Enables searching for fields in the explorer page
- Enables searching though the schema in the SDL page
- Fixes flickering of tables due to refetch
Fixes ENG-4976
Fixes ENG-5043
Fixes ENG-5074

fix: schema and sdl page improvements and flickers

---

studio/src/components/layout/graph-layout.tsx

fix: graph select ui

---

cli/src/commands/contract/index.ts

Auth check was not implemented for contract commands

fix: auth check for contract commands

---

controlplane/src/core/composition/composer.ts

fix: set expiry for the jwt

---

otelcollector/Dockerfile
otelcollector/otelcol-builder.yaml

chore: upgrade otel collector 0.101.0

---

studio/src/components/graph-visualization.tsx

fix: graph visualization toggle

---

controlplane/src/core/controllers/scim.ts

fix: remove unused attributes

---

router-tests/telemetry_test.go
router-tests/testenv/testenv.go
router/cmd/instance.go
router/core/router.go
router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/testdata/config_defaults.json
router/pkg/config/testdata/config_full.json
router/pkg/trace/config.go
router/pkg/trace/meter.go

Config proposal
```yaml
telemetry:
tracing:
sampling_rate: 1
parent_based_sampler: false
```

feat: allow to disable parent based sampling

---

router/core/factoryresolver.go

fix: propagate resolvable false

---

controlplane/src/core/repositories/analytics/AnalyticsDashboardViewRepository.ts
controlplane/src/core/repositories/analytics/AnalyticsRequestViewRepository.ts
controlplane/src/core/repositories/analytics/MetricsRepository.ts
controlplane/src/core/repositories/analytics/MonthlyRequestViewRepository.ts
controlplane/src/core/repositories/analytics/RouterMetricsRepository.ts
controlplane/src/core/repositories/analytics/SubgraphMetricsRepository.ts
controlplane/src/core/repositories/analytics/UsageRepository.ts
docker-compose.yml

fix: query source table instead of MV to avoid type mismatch

---

connect/src/wg/cosmo/platform/v1/platform_pb.ts
proto/wg/cosmo/platform/v1/platform.proto

The run id causes overflow. The frontend does not need it. Removed it altogether

fix: remove unused check run id causing overflow

---

studio/src/components/checks/changes-table.tsx
studio/src/components/checks/override.tsx
studio/src/components/subgraphs-table.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/analytics/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/subgraphs.tsx
studio/src/pages/[organizationSlug]/members.tsx

Query keys required inputs to invalidate correctly.

fix: incorrect query key for invalidation

---

studio/src/components/analytics/trace-details.tsx

fix: potential fix to always show graphql variables

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/compositions/[compositionId]/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/index.tsx

fix: fallback to router schema if client schema does not exist

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/repositories/GitHubRepository.ts

fix: missing namespace in github check details link

---

studio/src/components/app-provider.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/sdl.tsx

fix: set transport on org change

---

studio/src/components/schema/sdl-viewer-monaco.tsx

fix: poor performance on sdl due to anchor tags

---

cli/src/commands/contract/commands/create.ts
cli/src/commands/graph/federated-graph/commands/create.ts
cli/src/commands/graph/federated-graph/commands/update.ts
cli/src/commands/graph/monograph/commands/create.ts
cli/src/commands/graph/monograph/commands/update.ts
connect/src/wg/cosmo/platform/v1/platform_pb.ts
controlplane/migrations/0089_swift_malice.sql
controlplane/migrations/meta/0089_snapshot.json
controlplane/migrations/meta/_journal.json
controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/composition/composer.ts
controlplane/src/core/repositories/ContractRepository.ts
controlplane/src/core/repositories/FederatedGraphRepository.ts
controlplane/src/core/services/AdmissionWebhookController.ts
controlplane/src/db/schema.ts
controlplane/src/types/index.ts
proto/wg/cosmo/platform/v1/platform.proto

Sign requests made to the admission webhook endpoint if applicable.

feat: admission webhook signature

---

cli/src/commands/subgraph/commands/create.ts

fix: match option ref to -edg flag

---

cli/package.json
cli/src/commands/router/commands/compose.ts
pnpm-lock.yaml
studio/src/components/federatedgraphs-cards.tsx

fix: migrate button should respect namespace

---

router-tests/integration_test.go
router/core/graphql_prehandler.go

This PR ensures that the api returns JSON by default unless someone makes a file upload request. In the future, we could be more restrict and validate the content-types accordingly.

fix: support charset in content-type

---

controlplane/migrations/0092_open_marvex.sql
controlplane/migrations/meta/0092_snapshot.json
controlplane/migrations/meta/_journal.json
controlplane/src/bin/seed-billing.ts
controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/composition/composer.ts
controlplane/src/core/repositories/GraphCompositionRepository.ts
controlplane/src/db/schema.ts
demo/deploy.sh

fix: limit check and remove router_config_path

---

cli/src/commands/router/commands/compose.ts

fix: router compose command

---

studio/src/components/feature-flag-details.tsx

fix: feature flag details ui

---

pnpm-lock.yaml
studio/package.json

fix: upgrade next due to CVE-2024-34351

---

.github/workflows/playground-ci.yaml
playground/package.json

fix: playground scripts

---

scripts/create-cli-demo.sh

fix: create cli demo script

---

controlplane/package.json
controlplane/src/core/build-server.ts
controlplane/src/core/workers/AIGraphReadmeWorker.ts
pnpm-lock.yaml

fix(controlplane): graceful hutdown

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/core/repositories/SchemaCheckRepository.ts
controlplane/test/check-subgraph-schema.test.ts

This breaking change was introduced in drizzle [here](https://orm.drizzle.team/learn/latest-releases/drizzle-orm-v0300#breaking-changes).

fix: incorrect typecast on timestamp from db

---

controlplane/test/admission-webhook.test.ts

test: admission webhook header

---

controlplane/src/bin/delete-user.ts
helm/cosmo/charts/controlplane/templates/activate-organization.yaml
helm/cosmo/charts/controlplane/templates/deactivate-organization.yaml

Incorrect conditions in org jobs and log in delete user

fix: org activation jobs and delete user script

---

go.work.sum
router-tests/telemetry_test.go
router/core/context.go
router/core/modules.go
router/core/transport.go
router/go.mod
router/go.sum

fix: race for sendError, add test for sampling

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/routers.tsx

fix: increase page size for router page

---

studio/src/components/layout/subgraph-layout.tsx
studio/src/pages/[organizationSlug]/members.tsx

Completes ENG-5480
Completes ENG-5450

fix: invite members modal and subgraph selector

---

studio/src/components/analytics/field-usage.tsx

https://github.com/user-attachments/assets/49e68e38-07b0-407d-9919-23a2c8831adf

fix: tick formatter for custom date ranges

---

helm/cosmo/Chart.yaml
helm/cosmo/README.md
helm/cosmo/charts/otelcollector/Chart.yaml
helm/cosmo/charts/otelcollector/README.md

Bumps version for the main chart and the otelcollector helmchart.

feat: enable native support for prometheus for all instrumented

---

router/cmd/instance.go
router/core/graph_server.go
router/core/router.go
router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/testdata/config_defaults.json
router/pkg/config/testdata/config_full.json
router/pkg/cors/cors.go
router/pkg/cors/cors_test.go

feat: allow disabling cors

---

docker-compose.yml

chore(dev): different prom port for local otel setup

---

helm/cosmo/Chart.yaml
helm/cosmo/README.md

chore: bump helm chart version

---

router/__schemas/README.md

chore: update config instructions in readme

---

controlplane/src/core/webhooks/OrganizationWebhookService.ts

fix: incorrect deletions count in slack notification

---

demo/deploy.sh
scripts/create-cli-demo.sh
scripts/create-local-demo.sh
scripts/update-demo.sh

chore: update demo scripts

---

cli/src/commands/router/commands/compose.ts
controlplane/src/core/workers/AIGraphReadmeWorker.ts
controlplane/src/core/workers/DeleteOrganizationWorker.ts
demo/cmd/test1/README.md
demo/cmd/test1/main.go
demo/run_subgraphs.sh
router/__schemas/compose.sh
router/__schemas/graph.yaml

fix(cli-compose): feature subgraph introspection

---

aws-lambda-router/go.mod
aws-lambda-router/go.sum
demo/go.mod
demo/go.sum
go.work.sum
router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

chore: engine version bump

---

examples/full-cosmo-docker/README.md

chore: fix link in full cosmo docker example

---

examples/full-cosmo-helm/README.md
examples/full-cosmo-helm/create_demo.sh

chore(examples): fix typo in command

---

controlplane/src/core/services/AdmissionWebhookController.ts
controlplane/src/core/util.ts
controlplane/src/core/webhooks/OrganizationWebhookService.ts
controlplane/src/core/webhooks/PlatformWebhookService.ts
controlplane/src/core/webhooks/RedeliverWebhookService.ts

fix: retry webhook POST requests

---

studio/src/components/app-provider.tsx
studio/src/pages/[organizationSlug]/feature-flags/index.tsx
studio/src/pages/[organizationSlug]/graphs.tsx
studio/src/pages/[organizationSlug]/lint-policy.tsx
studio/src/pages/[organizationSlug]/subgraphs.tsx

fix: conflicting requests on reload and dashboard

---

cli/src/commands/graph/federated-graph/commands/fetch.ts

fix: graph fetch base path

---

CONTRIBUTING.md
README.md

chore: add contributing section

---

studio/src/components/app-provider.tsx
studio/src/pages/[organizationSlug]/settings.tsx
studio/src/pages/account/invitations.tsx

fix: features aren't shown as enabled after enabling them

---

controlplane/src/core/repositories/FeatureFlagRepository.ts
controlplane/src/core/repositories/SubgraphRepository.ts
studio/src/components/subgraphs-table.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/subgraphs.tsx
studio/src/pages/[organizationSlug]/[namespace]/subgraph/[subgraphSlug]/index.tsx
studio/src/pages/[organizationSlug]/subgraphs.tsx

feat: display and filter for subgraph id

---

helm/cosmo/charts/cdn/Chart.yaml
helm/cosmo/charts/cdn/README.md
helm/cosmo/charts/controlplane/Chart.yaml
helm/cosmo/charts/controlplane/README.md
helm/cosmo/charts/graphqlmetrics/Chart.yaml
helm/cosmo/charts/graphqlmetrics/README.md
helm/cosmo/charts/otelcollector/Chart.yaml
helm/cosmo/charts/otelcollector/README.md
helm/cosmo/charts/router/Chart.yaml
helm/cosmo/charts/router/README.md
helm/cosmo/charts/studio/Chart.yaml
helm/cosmo/charts/studio/README.md

chore: update AppVersions to latest service releases

---

aws-lambda-router/go.mod
aws-lambda-router/go.sum
demo/go.mod
demo/go.sum
router-tests/go.mod
router-tests/go.sum
router-tests/testdata/fixtures/query_plans/only_query_plan.json
router-tests/testdata/fixtures/query_plans/query_plan_with_trace_no_data.json
router-tests/testdata/fixtures/query_plans/response_with_query_plan.json
router/core/factoryresolver.go
router/go.mod
router/go.sum
router/pkg/graphqlschemausage/schemausage_test.go

fix: planning of provides, parent entity jump, conditional implicit keys, external fields

---

helm/cosmo/charts/cdn/Chart.yaml
helm/cosmo/charts/cdn/README.md
helm/cosmo/charts/controlplane/Chart.yaml
helm/cosmo/charts/controlplane/README.md

chore: helm bump to latest appVersions

---

controlplane/src/core/composition/composer.ts

fix: log config upload failures as errors

---

router-tests/integration_test.go
router/cmd/instance.go
router/core/graph_server.go
router/core/router.go

improve existing PR by making proxy configurable on the core & adding a basic test to validate that configuring the proxy works

feat: enable using HTTP(S)_PROXY in router

---

router-tests/integration_test.go
router-tests/nats_events_test.go
router-tests/structured_logging_test.go
router-tests/testenv/testenv.go
router-tests/tls_test.go

As we add in further structured logging, introducing a way to validate logs is critical to testing the full scope of the code. This code is inspired by the work of @Noroth
Completes ENG-5611

feat:  Add structured logging testing

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/src/db/models.ts

feat: add audits for enabling and disabling of feature flags

---

cli/src/commands/graph/federated-graph/commands/list.ts
cli/src/commands/graph/monograph/commands/list.ts

feat: list only contracts for monographs

---

router/core/operation_processor.go

fix: setting cached operation name

---

router/core/executor.go
router/go.mod
router/go.sum
router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/fixtures/full.yaml
router/pkg/config/testdata/config_defaults.json
router/pkg/config/testdata/config_full.json

https://github.com/wundergraph/cosmo/issues/1156

feat: make the maximum recycleable parser cache size configurable

---

keycloak/theme/src/main/resources/theme/cosmo/login/layout-cloud-iam.ftl
keycloak/theme/src/main/resources/theme/cosmo/login/theme.properties

fix: keycloak theme css

---

graphqlmetrics/core/metrics_service.go

fix(collector): dont process empty schema usage metrics

---

router-tests/structured_logging_test.go
router-tests/testenv/testenv.go
router/core/graph_server.go
router/core/graphql_handler.go
router/internal/recoveryhandler/recovery.go
router/internal/requestlogger/requestlogger.go
router/pkg/logging/logging.go

fix(router): ensure consistent request logs in error conditions

---

helm/cosmo/README.md
helm/cosmo/values.yaml

chore: pin cosmo keycloak version in default values

---

router/core/header_rule_engine.go

Removes debugging printlns accidentally left in

fix: remove printlns

---

controlplane/src/core/repositories/analytics/TraceRepository.ts

Split it into 2 parts to avoid clickhouse behaviour.

fix: recursive query syntax

---

graphqlmetrics/core/metrics_service.go

fix: handle empty batch of metrics

---

controlplane/src/core/repositories/analytics/TraceRepository.ts

fix: apply filters to recursive part

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/checks/[checkId]/index.tsx

fix: reason for check status

---

controlplane/src/core/bufservices/PlatformService.ts
controlplane/test/feature-flag/get-feature-flags.test.ts
controlplane/test/feature-subgraph/get-feature-subgraphs.test.ts
controlplane/test/federated-graph.test.ts
controlplane/test/subgraph/get-subgraphs.test.ts

fix: return error if the namespace doesnt exist while listing graphs

---

router-tests/websocket_test.go
router/core/websocket.go

Issue is described in detail here https://github.com/wundergraph/cosmo/issues/1238
I have added the nil check and written a test that fails before the change and succeeds after.

fix: fix panic when accessController is nil in handleUpgradeRequest

---

router/core/graph_server.go
router/core/operation_processor.go
router/core/operation_processor_test.go

fix: return error when introspection query is made when disabled

---

helm/cosmo/charts/router/Chart.yaml
helm/cosmo/charts/router/README.md
helm/cosmo/charts/router/templates/deployment.yaml
helm/cosmo/charts/router/values.yaml

feat: make router config an explicit property update AppVersion

---

.github/workflows/image-release.yml

chore: login in early to docker to avoid rate limiting issues

---

router-tests/websocket_module_test.go
router/core/websocket.go

This PR fixes a websocket regression for custom modules. An integration test has been added to prevent it in the future.

fix(websocket): set op name and operation

---

router/core/websocket.go

fix(websocket): check for valid fd

---

router/core/operation_metrics.go
router/core/operation_planner.go

fix: exclude query plan fetches from field usage count

---

router-tests/modules/module_test.go
router/cmd/custom/module/module.go
router/core/graph_server.go

fix: trace id in logs from custom modules

---

controlplane/migrations/0103_heavy_jazinda.sql
controlplane/migrations/0103_sparkling_leper_queen.sql
controlplane/migrations/meta/0103_snapshot.json
controlplane/migrations/meta/_journal.json
controlplane/src/db/schema.ts

fix: include tags migration

---

.github/workflows/cdn-ci.yaml
.github/workflows/cli-ci.yaml
.github/workflows/composition-ci.yaml
.github/workflows/controlplane-ci.yaml
.github/workflows/playground-ci.yaml
.github/workflows/release-preview.yaml
.github/workflows/release.yaml
.github/workflows/shared-ci.yaml
.github/workflows/studio-ci.yaml
cli/README.md
cli/package.json
pnpm-lock.yaml

chore(cli): add scarf to track cli usage

---

cli/src/commands/contract/commands/create.ts
cli/src/commands/contract/commands/update.ts

fix: handle undefined tag arrays

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/index.tsx

fix: improve contract tags ui in the graph overview

---

router/core/websocket.go

fix(epoll): don't return when client conn was terminated

---

controlplane/migrations/0106_secret_bill_hollister.sql
controlplane/migrations/0106_sweet_mad_thinker.sql
controlplane/migrations/meta/0106_snapshot.json
controlplane/migrations/meta/_journal.json
controlplane/src/db/schema.ts

feat(perf): improve graph composition queries

---

router-tests/structured_logging_test.go
router/core/graph_server.go

fix(access-logs): default value is not respected without value_from

---

router/pkg/config/config.schema.json

fix: propagate new yaml properties in schema.json

---

studio/next.config.mjs

This broke our current release pipeline.

fix: assert from nextjs config

---

cli/src/commands/router/commands/compose.ts

feat: display warning in wgc router compose command

---

router-tests/automatic_persisted_queries_test.go
router/internal/persistedoperation/apq/client.go
router/internal/persistedoperation/apq/redis.go
router/pkg/config/config.go

This solves two issues pointed out: 
* We want to enable customers to inject a secure redis url, with auth, rather than having it in a config file that can be read. 
* While Persisted Operations need to be bound by client (see #1179), APQ should not be, because it's meant to share operations across clients. This PR ensures that that works, even with a local cache

fix: enable redis url injection via env var, allow apq from diff clients

---

router-tests/telemetry_test.go
router/pkg/metric/meter.go

fix(router): use OTLP separators for regex

---

aws-lambda-router/go.mod
aws-lambda-router/go.sum
demo/go.mod
demo/go.sum
router-tests/go.mod
router-tests/go.sum
router-tests/integration_test.go
router/core/operation_processor.go
router/go.mod
router/go.sum

fix: variables normalization for the anonymous operations

---

aws-lambda-router/go.mod
aws-lambda-router/go.sum
demo/go.mod
demo/go.sum
router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

fix: fix merging of response nodes of enum type

---

aws-lambda-router/go.mod
aws-lambda-router/go.sum
demo/go.mod
demo/go.sum
router-tests/go.mod
router-tests/go.sum
router-tests/websocket_test.go
router/go.mod
router/go.sum

Related: https://github.com/wundergraph/graphql-go-tools/pull/982

fix(tests): deadlock on unsubscribe when epoll disabled

---

router-tests/cors_test.go
router/pkg/cors/cors.go
router/pkg/cors/cors_test.go

fix(router): ensure that cors wildcard support is enabled

---

demo/go.mod
demo/go.sum
router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

fix: fix regression on removing null variables which was undefined

---

studio/src/components/checks/operations.tsx
studio/src/components/ui/pagination.tsx

fix: pagination ui of operations

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/checks/[checkId]/index.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/compositions/[compositionId]/index.tsx

fix: text overflow of composition errors and warnings

---

CONTRIBUTING.md
router/pkg/config/config.schema.json

docs: improve development documentation

---

studio/src/components/ui/dropdown-menu.tsx

fix: scrollable dropdown

---

router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/testdata/config_defaults.json

fix: have enable_subgraph_fetch_operation_name default to false

---

.github/workflows/aws-lambda-router-ci.yaml
.github/workflows/graphqlmetrics-ci.yaml
.github/workflows/helm-ci.yaml
.github/workflows/router-ci.yaml

`actions/setup-go` comes already with a cache. This change also speeds up the CI.

chore: remove duplicated cache action

---

router-tests/structured_logging_test.go
router/core/executor.go
router/core/router.go
router/pkg/pubsub/nats/nats.go

feat: add NATS reconnect handling

---

router-tests/nats_events_test.go
router-tests/structured_logging_test.go
router/core/executor.go

chore: improve NATS connection message

---

router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/fixtures/full.yaml
router/pkg/config/testdata/config_defaults.json
router/pkg/config/testdata/config_full.json

fix: update default value for subgraph fetch operation name

---

router-tests/normalization_test.go

chore: update the test cases for normalization tests

---

studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/analytics/index.tsx
studio/src/pages/[organizationSlug]/apikeys.tsx

fix: remove double frontend requests to controlplane

---

controlplane/src/core/build-server.ts
controlplane/src/core/plugins/clickhouse.ts
controlplane/src/core/routes.ts

chore: reduce the timeout for clickhouse and platform service

---

controlplane/src/core/services/ApiGenerator.ts

fix: use secure variant of id generator

---

demo/cmd/availability/main.go

fix: availability subgraph in the demo

---

router/core/router.go

chore(router): incorrect metric config

---

controlplane/src/core/bufservices/analytics/getOperationContent.ts
controlplane/src/core/repositories/CacheWarmerRepository.ts
graphqlmetrics/gen/proto/wg/cosmo/graphqlmetrics/v1/graphqlmetrics.pb.go
proto/wg/cosmo/graphqlmetrics/v1/graphqlmetrics.proto
router/core/graph_server.go
router/gen/proto/wg/cosmo/graphqlmetrics/v1/graphqlmetrics.pb.go
studio/src/components/cache/cache-details-sheet.tsx
studio/src/components/code-viewer.tsx

This PR comes with the following improvements:
- Don't abort the router start or config update when the cache errors for any reasons e.g. after max retry of PO download
- Don't include client version and name to the operations manifest when unknown values like `missing`, `unknown` are used.
- PersistentId was not displayed in the UI due to a typo.
- Don't pretty print cache operations because a user wants to understand what's the exact operation content in the cache
- Catch nil-pointer exception when operation content is empty.

fix(cache operation): swallow cache errors and other improvements

---

router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

Upgrade engine to get this fix: https://github.com/wundergraph/graphql-go-tools/pull/1043

fix: remove semaphore from ResolveGraphQLSubscription

---

studio/src/pages/[organizationSlug]/[namespace]/subgraph/[subgraphSlug]/index.tsx

fix: add copy button to subgraph routing url

---

controlplane/src/bin/billing.json

This PR reduces the duration of breaking change retention to 30 days.

fix: reduce the breaking change retention duration

---

controlplane/src/core/repositories/OrganizationRepository.ts
studio/src/pages/[organizationSlug]/usages.tsx

This PR changes the defaults of breaking change retention limit.

fix: change the defaults of breaking-change-retention

---

router-tests/go.mod
router-tests/go.sum
router-tests/testenv/testenv.go

chore: reduce verbose logging for failed tests

---

.github/workflows/router-ci.yaml
docker-compose.yml
docker/redis/redis-cluster-create.sh
docker/redis/redis-cluster.conf
router-tests/automatic_persisted_queries_test.go
router-tests/ratelimit_test.go
router-tests/testenv/testenv.go
router/internal/persistedoperation/operationstorage/redis/rdcloser.go
router/internal/persistedoperation/operationstorage/redis/rdcloser_test.go
router/pkg/config/config.schema.json

Previous work at refactoring the redis connection added a regression, where we weren't handling redis authentication appropriately. This PR introduces a number of fixes:
* Correctly parse redis cluster URLs and parse options using the designated `ParseClusterOptions`
* Ensure that we only provide auth if added
* Add integration tests with ADL protected redis cluster
Fixes #1557

fix(router): enable redis to work with auth

---

cdn-server/package.json
controlplane/package.json
graphqlmetrics/package.json
keycloak/package.json
otelcollector/package.json
router/package.json
studio/package.json

NodeJS oneliner is slower and harder to read than using `jq` for this purpose.

refactor: use jq instead of node to extract values from package.json

---

router-tests/cache_warmup_test.go
router-tests/integration_test.go
router/core/cache_warmup.go
router/core/graph_server.go
router/core/graphql_prehandler.go
router/core/operation_processor.go
router/core/websocket.go
router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/testdata/config_defaults.json
router/pkg/config/testdata/config_full.json

Sometimes you may want to preserve original variables names in calls to a subgraph

feat: add a flag to disable variables remapping

---

demo/go.mod
demo/go.sum
router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

fix: querying fields under external path used in a composite key with nested fields

---

router/pkg/config/config.go

fix: apollo router compatibility yaml property

---

demo/go.mod
demo/go.sum
router-tests/Makefile
router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

Engine release: https://github.com/wundergraph/graphql-go-tools/pull/1074

fix(engine): deadlock when waiting on inflight events of a trigger

---

router/core/graph_server.go
router/internal/middleware/cookie_filter.go
router/internal/middleware/cookie_filter_test.go

fix: add a hardcoded cookie whitelist for internal cookie names

---

cdn-server/cdn/test/cdn.test.ts
studio/src/pages/[organizationSlug]/cache-warmer.tsx

chore: typo opeartions -> operations

---

demo-router.fly.toml
demo/go.mod
demo/go.sum
router-tests/go.mod
router-tests/go.sum

go.mod is out of sync. Additionally, I updated our demo router app on fly.

chore(demo): update lock and fly config

---

router-tests/go.mod
router/Makefile
router/go.mod
router/go.sum

* fix node selections do not select external parents of unique node ([#1087](https://github.com/wundergraph/graphql-go-tools/issues/1087)) ([6adc0f6](https://github.com/wundergraph/graphql-go-tools/commit/6adc0f69b40d1aa6bf8bd660cfdea6327b93ce1b))

fix: fix node selections do not select external parents of unique node

---

cli/package.json
cli/src/core/config.ts
cli/tsconfig.json
pnpm-lock.yaml

- Changes `tsconfig.json` to set `rootDir` which should make `dist` folder structure constant in the future
- Adds import assertion and doesn't do esmodule import from json

fix: correct and deterministic dist folder structure

---

.github/workflows/release.yaml

Versioning in CLI releases is wrong currently due to the build happening before `package.json` is updated in `lerna publish`. I looked pretty deep into lerna docs to see if I could do this more "correctly" by separating the version and publish commands, but nothing seems to work except running "version" and then using your own script to handle publishing.
I'd like not to fix what isn't broken, so I do the simple thing and dry-run the release (which adds changelog and `package.json` and reset before and after building.

ci: dry-run versioning before release build

---

demo/go.mod
demo/go.sum
router-tests/go.mod

chore: update router version in demo

---

router/core/parse_multipart.go

fix: reading file uploads map by ignoring actual indices in map

---

cli/.gitignore
cli/e2e/smoke.test.ts
package.json
patches/graphql@16.9.0.patch
pnpm-lock.yaml

Bun runs into a bundling [issue](https://github.com/oven-sh/bun/issues/3659#issuecomment-1638996538) with the graphql package. This PR patches the package.json to avoid any dual-package hazard. We remove ESM support. This is not the only time where we run into import issues with the graphql package. We patched it already for tests [here](https://github.com/wundergraph/cosmo/blob/main/composition/vite.config.ts#L6). It is good that we now enforce it globally.

fix(cli): bun bundle issue with graphql dual-package hazard issue

---

helm/cosmo/Chart.yaml
helm/cosmo/README.md
helm/cosmo/charts/cdn/Chart.yaml
helm/cosmo/charts/cdn/README.md
helm/cosmo/charts/controlplane/Chart.yaml
helm/cosmo/charts/controlplane/README.md
helm/cosmo/charts/graphqlmetrics/Chart.yaml
helm/cosmo/charts/graphqlmetrics/README.md
helm/cosmo/charts/otelcollector/Chart.yaml
helm/cosmo/charts/otelcollector/README.md
helm/cosmo/charts/router/Chart.yaml
helm/cosmo/charts/router/README.md
helm/cosmo/charts/studio/Chart.yaml
helm/cosmo/charts/studio/README.md

This PR updates the versions of the packages in their respective helm charts

feat: update package versions in helm charts

---

examples/full-cosmo-helm/README.md

This PR updates the README to use the latest version of the helm charts

chore: update README

---

cli/src/commands/graph/common/version/commands/set.ts
cli/src/commands/graph/common/version/index.ts
cli/src/commands/graph/federated-graph/index.ts
cli/src/commands/graph/monograph/index.ts

This PR fixes the issue where even if the namespace is passed its not being considered

fix: namespace not being considered in version set command

---

pnpm-lock.yaml
studio/package.json

I have upgraded the `next` package by removing and reinstalling it in studio in order to solve a vulnerability caused by version `<= 14.2.21`
This was achieved with the following commands:
```
cd studio
pnpm remove next
pnpm add next@14.2.24
```

fix: upgrade `next` dependency to solve vulnerability

---

demo/go.mod
demo/go.sum
router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum
router/internal/expr/expr.go

This PR resolves https://avd.aquasec.com/nvd/2025/cve-2025-29786/

fix: upgrade expr package

---

.github/workflows/cli-ci.yaml
.github/workflows/controlplane-ci.yaml

chore: update CI workflows to include 'shared' directory in triggers

---

router-tests/structured_logging_test.go
router/core/graph_server.go
router/internal/expr/expr.go

This PR adds the ability to check if the request has been sampled. It also adds the following structure to the existing expression context.
```
trace {
sampled: bool
}
```
We check if the span context is sampled using the `IsSampled()` method and set the value to the expression context's `request.trace.sampled` attribute.
Note: This pr is pointed to my other expression body PR, it will be pointed to origin/main after it's merged.

feat: add the ability to check if the request has been sampled using the expression context

---

router-tests/structured_logging_test.go
router/core/graphql_prehandler.go
router/core/request_context_fields.go

The subgraph error codes are not propagated when we fail the validation, because they are only propagated right now when there are errors after a subgraph call. This will add any error codes from the validation step to the requestContext's errorCodes.
This fix will allow errorCodes from the validation step to be logged.
This PR also fixes nil pointer panics on the request logger for the start of a web socket request. See below for screenshot of websocket request.

fix: subgraph error code is not propagated AND panics on websocket request logging

---

controlplane/src/bin/billing.json

This PR adds one feature flag to the developer plan

feat: add one feature flag to developer plan

---

router-tests/variables_validation_test.go
router/core/graph_server.go
router/core/operation_processor.go
router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/testdata/config_defaults.json
router/pkg/config/testdata/config_full.json

feat: add option to disable exposing variables content on validation error

---

.github/workflows/pr-description.yml

This PR adds a workflow to ensure that every PR has a description. PR descriptions are useful for reviewers and customers who observe our work. You can simplify the generation via GitHub Copilot Pull request summaries.

chore: add workflow to enforce PR description

---

controlplane/src/core/bufservices/subgraph/checkSubgraphSchema.ts
controlplane/src/core/composition/composer.ts

This reverts to use the old method for composing subgraphs in checks

fix: subgraph check compose

---

.github/workflows/pr-description.yml

This PR adds a check to the PR description workflow to ignore release please PRs

chore: ignore release please for workflow

---

helm/cosmo/charts/router/Chart.yaml
helm/cosmo/charts/router/README.md

This PR bumps the router chart version to trigger the deployment process.

fix: bump router chart version

---

controlplane/src/core/repositories/SubgraphRepository.ts

This PR fixes the filter of checks to return based on subgraphID

fix: filter of checks

---

router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

This pull request updates the `go.mod` files for the `router-tests` and `router` modules to use a newer version of `github.com/wundergraph/graphql-go-tools/v2` and modifies commented-out `replace` directives for clarity.
Dependency updates:
* Updated `github.com/wundergraph/graphql-go-tools/v2` from `v2.0.0-rc.170` to `v2.0.0-rc.171` in `router-tests/go.mod` and `router/go.mod`. [[1]](diffhunk://#diff-87ed942eb7f6bf4c8ffb7554727d7978c1c12c744c2374c6d6986058a82664bbL29-R29) [[2]](diffhunk://#diff-ce13a34568eacc644308751a32da2ff0da7fa70a337082bc198581ab1bac0d15L34-R34)
Related Engine PR: https://github.com/wundergraph/graphql-go-tools/pull/1127

fix(subscriptions): dont use completed channel in sub updater

---

router/pkg/config/config.schema.json
router/pkg/metric/noop_metrics.go

We accidentally added fields to the required fields that aren't necessary. However, I added `endpoint`, which is always required.

fix: s3 remove unnecessary required fields in json schema

---

router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

* add static resolver of root operation types __typename fields ([#1128](https://github.com/wundergraph/graphql-go-tools/issues/1128)) ([3dc79f1](https://github.com/wundergraph/graphql-go-tools/commit/3dc79f18694ff83782a200f7f59541038a29655c))
* add support of fragments in the provides directive ([ca2e6c2](https://github.com/wundergraph/graphql-go-tools/commit/ca2e6c2e4fd6f601f9e72faefc922dba9a0fc01d))
* add support of inline fragments to representation variables builder; add typename selection to requires selection set in case it has fragments ([40e3fd9](https://github.com/wundergraph/graphql-go-tools/commit/40e3fd95c35fa2a0a46eee58c7ebdc75595e41f1))
* add support of inline fragments in requires directive, add an alias for required fields in case of conflict …

feat: rework key matching logic, add engine support for fragments in provides/requires

---

.github/workflows/graphqlmetrics-ci.yaml
docker-compose.full.yml
docker-compose.yml

This PR sync the local version with the version on cloud to ensure reproducibility.

chore: sync clickhouse version with cloud

---

router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

Update engine to [v2.0.0-rc.176](https://github.com/wundergraph/graphql-go-tools/releases/tag/v2.0.0-rc.176)
* evaluate keys using order of target subgraph ([#1139](https://github.com/wundergraph/graphql-go-tools/issues/1139)) ([f358e9e](https://github.com/wundergraph/graphql-go-tools/commit/f358e9e74c16f0c372170d9cde82decbf4991289))

fix: evaluate keys using order of target subgraph

---

router-tests/testenv/testenv.go
router/core/router.go
router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/fixtures/full.yaml
router/pkg/config/testdata/config_defaults.json
router/pkg/config/testdata/config_full.json
router/pkg/mcpserver/server.go

Allows the use of `mcp.server.listen_addr` to define the listen address on which the MCP gateway is exposed. This aligns it with other HTTP server configurations.
```yaml
mcp:
enabled: true
expose_schema: true
enable_arbitrary_operations: true
server:
listen_addr: localhost:5025
storage:
provider_id: "mcp"
storage_providers:
file_system:
- id: "mcp"
path: "operations"
```

feat: expose mcp listen addr for full flexibility

---

controlplane/src/bin/billing.json
controlplane/test/feature-subgraph/create-feature-subgraph.test.ts
controlplane/test/proposal/create-proposal.test.ts
controlplane/test/proposal/proposal-schema-match.test.ts
controlplane/test/proposal/update-proposal.test.ts
studio/src/components/layout/graph-layout.tsx
studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/proposals/index.tsx
studio/src/pages/[organizationSlug]/policies.tsx

This PR makes proposals a invite only feature

fix: make proposals a invite only feature

---

.github/workflows/router-ci.yaml
router/README.md

Right now if flaky integration tests fail we need to rerun the entire stack, which means that integration tests can fail on the second run. Creating an endless cycle, we separate out the jobs for now so we can restart them independently.

fix: split flaky and non flaky integration jobs

---

router-tests/go.mod
router-tests/go.sum
router-tests/mcp_test.go
router/core/router.go
router/go.mod
router/go.sum
router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/fixtures/full.yaml
router/pkg/config/testdata/config_defaults.json
router/pkg/config/testdata/config_full.json
router/pkg/mcpserver/server.go

This PR adds support for a custom baseURL. The baseURL defines the on what address the MCP server will be reachable. The URL is communicated as part of the MCP protocol. I also removed the fallback to the listen addr of the router because MCP supports a relative base URL. I also upgraded mcp-go library to the latest version which fixes many issues and improves stability.

feat: add support for mcp base server url, upgrade mcp-go

---

.github/actions/cli-build/action.yml
.github/workflows/cli-binary-release.yaml
.github/workflows/cli-ci.yaml
cli/README.md
cli/package.json
cli/src/commands/index.ts
cli/src/core/telemetry.ts
cli/src/index.ts
pnpm-lock.yaml
studio/next.config.mjs
studio/package.json
studio/src/components/app-provider.tsx
studio/src/components/user-menu.tsx
studio/src/lib/posthog.ts
studio/src/lib/track.ts
studio/src/pages/_app.tsx

This adds posthog to the studio.

feat: add posthog

---

studio/src/lib/track.ts

…using undefined distinct id
Do not override posthog id with custom id

fix: update PostHog identification to allow cross-domain tracking

---

cli/README.md

This pull request significantly enhances the `cli/README.md` documentation for the WunderGraph Cosmo CLI (`wgc`). It introduces a more structured, detailed, and visually appealing format, making it easier for users to understand and get started with the CLI. The changes include an overview of features, installation instructions, usage examples, and links to related resources.
* **Introduction and Overview**: Added a detailed introduction to `wgc`, highlighting its purpose, key features, and use cases. This provides a clearer context for new users.
* **Cosmo Features Section**: Introduced a comprehensive list of features, including federation support, schema registry, composition checks, observability, and access control.
* **Installation and Getting Started**: Expanded the installation …

chore: update wgc cli README

---

.github/actions/cli-build/action.yml
.github/workflows/cli-binary-release.yaml
.github/workflows/cli-ci.yaml
.github/workflows/release.yaml
cli/src/core/telemetry.ts
package.json

Uses the correct env and also gets the orgSlug correctly

fix: posthog cli env

---

cli/src/core/telemetry.ts

Check if CLI is talking to cosmo cloud

fix: check if CLI is connected to Cosmo Cloud

---

router/core/operation_processor.go
router/core/operation_processor_test.go

Under rare circumstances we were not updating normalized representations and variables

fix: variables normalization

---

cli/src/commands/router/commands/compose.ts
cli/src/commands/router/plugin/templates/go-plugin.ts
cli/src/commands/router/plugin/toolchain.ts

This PR updates the file and module references to the latest stable release. Additionally, we validate if the plugin version is given and follows semver.

chore: update release references, validate plugin version

---

cli/src/commands/router/plugin/templates/plugin.ts

Fixes a mistake in the cursor rules about the http client usage

fix(wgc): cursor instructions for plugin http client usage

---

cli/src/commands/router/plugin/commands/init.ts
cli/src/commands/router/plugin/templates/plugin.ts

This significantly improves the cursor rules by being more direct and informing the model about the exact plugin directory path.

feat(cli): improve cursor rules

---

router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum
router/pkg/mcpserver/server.go

This pull request includes updates to dependencies, enhancements to the server configuration, and minor refactoring for improved code clarity and functionality. The most significant changes include updating the `mark3labs/mcp-go` dependency, improving the SSE server setup, and replacing `request.Params.Arguments` with `request.GetArguments()` for better API usage.
* Updated `mark3labs/mcp-go` from `v0.27.0` to `v0.30.0` in both `router-tests/go.mod` and `router/go.mod` to incorporate the latest features and fixes. [[1]](diffhunk://#diff-87ed942eb7f6bf4c8ffb7554727d7978c1c12c744c2374c6d6986058a82664bbL16-R16) [[2]](diffhunk://#diff-ce13a34568eacc644308751a32da2ff0da7fa70a337082bc198581ab1bac0d15L72-R72)
* Modified the SSE server configuration in `router/pkg/mcpserver/server.go` to use …

fix(mcp): enable PING events by default to prevent proxy timeouts

---

.github/workflows/router-ci.yaml
router-tests/Makefile
router-tests/events/kafka_events_test.go
router-tests/events/nats_events_test.go

Split tests to reduce impact of flaky tests.
Temporarly skipping Nats test "subscribing to a non-existent stream returns an error", while understanding what the issue is. I'll deploy the fix of this test with a separate PR.

chore: split tests

---

controlplane/src/core/bufservices/user/inviteUser.ts
controlplane/src/core/repositories/OrganizationGroupRepository.ts

This addresses an issue caused when trying to resend an invitation to a pending organization member.

chore: fix `resend invitation` issue

---

router-tests/go.mod
router-tests/go.sum
router-tests/testdata/queries/products.json
router-tests/websocket_module_test.go
router/go.mod
router/go.sum

Update engine
* handling nested abstract fragments in abstract fragments ([#1184](https://github.com/wundergraph/graphql-go-tools/issues/1184)) ([c3321d3](https://github.com/wundergraph/graphql-go-tools/commit/c3321d3cd72b63fbf5d7d949d70fd6dfeb73e2e1))

fix: handling nested abstract fragments in abstract fragments

---

cli/src/commands/graph/federated-graph/commands/list.ts
cli/src/commands/graph/monograph/commands/list.ts
cli/src/commands/router/commands/compatibility-version/commands/list.ts
cli/src/commands/router/commands/token/commands/list.ts
cli/src/commands/subgraph/commands/fetch.ts
cli/src/commands/subgraph/commands/introspect.ts
cli/src/commands/subgraph/commands/list.ts

We were importing the incorrect program causing circular dependencies and failing tests when imported

fix: incorrect import of program

---

adr/custom-modules-v1.md
router-tests/events/kafka_events_test.go
router-tests/testenv/testenv.go
router-tests/testenv/utils.go
router/pkg/config/config.go
router/pkg/config/config.schema.json
router/pkg/config/fixtures/full.yaml
router/pkg/config/testdata/config_full.json
router/pkg/pubsub/kafka/provider_builder.go

Writing the redis tests without any require inside go routines and using channels instead of timeouts has reduced the flakiness of those tests.
So in this PR I tried to do the same for kafka.
Working on this task I saw, inspecting the kafka client debug log, that when the test was failing, most of the time was spent on the fetch operation, so I also reduced the FetchMaxWait with really good results (locally).

test: improved kafka integration tests

---

router-tests/go.mod
router-tests/go.sum
router/go.mod
router/go.sum

Update engine
* fix rewriting object selections with nested abstract fragments ([#1192](https://github.com/wundergraph/graphql-go-tools/issues/1192)) ([a22b89c](https://github.com/wundergraph/graphql-go-tools/commit/a22b89c4379db027e3e5be99670cc14d037c1894))

fix: fix rewriting object selections with nested abstract fragments
