wundergraph/cosmo

- cli/src/commands/router/commands/compose.ts
Improves the input file structure for the router compose command
```yaml
version: 1
subgraphs:
- name: employees
routing_url: http://localhost:4001/graphql
schema:
file: ./employees.graphql
- name: family
routing_url: http://localhost:4002/graphql
introspection:
url: http://localhost:4002/graphql
headers:
Authorization: 'Bearer YOUR_TOKEN_HERE'
```
> fix: improve compose command input

- README.md
https://github.com/wundergraph/cosmo/tree/main/control-plane is a broken path referenced in the top-level README.md
> docs: fix broken path in README to control plane

- router/cmd/main.go
- router/core/context.go
- router/core/executor.go
- router/core/factoryresolver.go
- router/core/router.go
- router/core/transport.go
- router/go.mod
- router/go.sum
- router/internal/config/config.go
- router/internal/retrytransport/retry_transport.go
- router/internal/retrytransport/retry_transport_test.go
Implements backoff jitter retry for query operations
https://cosmo-docs.wundergraph.com/~/changes/VKKWOoLA1Kg0m70D5CDW/router/traffic-shaping
Introduce a breaking change where delays, and timeouts are parsed as Go duration (10s, 100ms) instead of suffixing all environment variables and config properties with _seconds)
> feat: implement backoff jitter retry mechanism

- router/cmd/main.go
- router/core/router.go
- router/internal/config/config.go
Users should be able to modify the path that the gateway uses when serving graphql requests. Currently this path is hardcoded to `/graphql` but similar to the `ListenAddr` it should be possible for the user to change it via configuration. This PR adds support for a new config `GraphQLPath` defined in the yaml and adds it to the configurator code at startup.
> feat(config): support configuration of graphql path

- router/core/transport.go
- router/internal/config/config.go
From now on when the user passes a custom config path and the file cannot be found an error is thrown and the server exits.
I have fixed #81 as well. I'll make this clear in the release notes as well.
> fix: add handlers to the custom transport / throw error on invalid cfg path

- controlplane/src/core/build-server.ts
The datetime format is much easier to understand
```
{"level":"debug","time":"2023-09-25T18:11:15.230Z","pid":89306,"hostname":"pop-os","msg":"Database connection healthcheck succeeded"}
```
> feat(controlplane): use datetime formatted logs

- cli/src/github.ts
GitHub ref and commit from env will be different as mentioned [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) so we need to read it from event json. Also cleaned up the file
> fix: cli reading incorrect github sha

- cli/src/commands/subgraph/commands/check.ts
> fix: repository and owner slug swapped

- router/cmd/instance.go
- router/cmd/main.go
This enables consumers to own the router lifecycle without needing access to the internals of the router library.
With the current set up it's not possible for consumers to manage the lifecycle of the router. This diff decouples router instantiation and router start up / shutdown, which gives consumers more flexibility as to how to manage the configuration and start the router.
> fix: (router) refactor cmd/main to expose router instance

- connect/package.json
- pnpm-lock.yaml
The package is unable to function at runtime without these dependencies, so they're actually runtime dependencies, not devDepedencies.
> fix: [connect] Move devDependencies to dependencies

- studio/src/components/analytics/field-usage.tsx
- studio/src/pages/[organizationSlug]/graph/[slug]/schema/index.tsx
> fix: view usage for enums and inputs

- router/internal/graphqlmetrics/aggregation.go
- router/internal/graphqlmetrics/aggregation_test.go
> fix: check equality of InputMetrics when aggregating same metrics

- router-tests/integration_test.go
- router-tests/websocket_test.go
- router/core/graphql_handler.go
- router/core/graphql_prehandler.go
- router/core/operation_planner.go
Instead of returning a generic message via HTTP/ws, use the error report
as returned by the engine.
> fix: provide more specific error messages when operation planning fails

- demo/pkg/subgraphs/employees/subgraph/schema.resolvers.go
- router-tests/authentication_test.go
- router-tests/headers_test.go
- router-tests/integration_test.go
- router-tests/singleflight_test.go
- router-tests/subgraph_errors_test.go
- router-tests/websocket_test.go
- Make most tests parallel
- Avoid generating the same configuration multiple times
- Make timings more tighter when possible, to make the tests not spend
so much time waiting
This reduces the runtime for the whole testsuite from ~180s to ~18s
> test: improve router test suite performance

- studio/src/components/playground/fetch-flow.tsx
> fix: alignment of URL button in trace tree view

- controlplane/migrations/0072_messy_silvermane.sql
- controlplane/migrations/meta/0072_snapshot.json
- controlplane/migrations/meta/_journal.json
- controlplane/src/core/bufservices/PlatformService.ts
- controlplane/src/core/repositories/OrganizationRepository.ts
- controlplane/src/core/services/Keycloak.ts
- controlplane/src/db/schema.ts
- When creating an organization through the new payment flow we forgot to add keycloak groups.
- When deleting an organization we delete targets and keys. We had a separate function for that. I added cascade constraints to the schema instead.
> fix: create keycloak groups when creating organization

- router-tests/go.sum
- router/core/websocket.go
- router/go.mod
- router/go.sum
- router/internal/epoller/README.md
- router/internal/epoller/conn.go
- router/internal/epoller/epoll.go
- router/internal/epoller/epoll_bsd.go
- router/internal/epoller/epoll_linux.go
- router/internal/epoller/epoll_test.go
- router/internal/epoller/epoll_unsupported.go
- router/internal/epoller/fd_test.go
I saw that our build broke because https://github.com/smallnest/epoller requires CGO on windows. The dependency on CGO is not worth it. We can reevaluate it once users reporting about performance issues on Windows.
> fix: disable epoll for windows to avoid CGO

- router/cmd/instance.go
- router/config.yaml
- router/core/operation_parser.go
- router/core/router.go
```
22:04:00 PM WARN No graph token provided. The following features are disabled. Not recommended for Production. {"component": "@wundergraph/router", "service_version": "dev", "features": ["Schema Usage Tracking", "Persistent operations", "Cosmo Cloud Tracing", "Cosmo Cloud Metrics"]}
22:04:00 PM WARN Development mode enabled. This should only be used for testing purposes {"component": "@wundergraph/router", "service_version": "dev"}
22:04:00 PM INFO event source {"component": "@wundergraph/router", "service_version": "dev", "provider": "NATS", "url": "nats://localhost:4222"}
22:04:00 PM INFO Prometheus metrics enabled {"component": "@wundergraph/router", "service_version": "dev", "listen_addr": "0.0.0.0:8088", "endpoint": "/metrics"}
22:04:00 PM INFO Static router config provided. …
```
> fix: allow to start router without graph token but static config

- router/cmd/instance.go
- router/core/router.go
- router/internal/graphiql/playgroundhandler.go
- router/pkg/config/config.go
> feat: allow custom playground path

- controlplane/src/core/plugins/database.ts
- controlplane/src/core/test-util.ts
- controlplane/vite.config.ts
On my machine it is not rare, that some tests take longer than 5s. Bootstrapping the server, including migration takes already ~2s.
> fix: wait until db is closed in close server hook

- helm/cosmo/charts/cdn/CHART.md
- helm/cosmo/charts/cdn/templates/_helpers.tpl
- helm/cosmo/charts/cdn/templates/deployment.yaml
- helm/cosmo/charts/cdn/templates/secret.yaml
- helm/cosmo/charts/cdn/values.yaml
- helm/cosmo/charts/controlplane/CHART.md
- helm/cosmo/charts/controlplane/templates/_helpers.tpl
- helm/cosmo/charts/controlplane/templates/clickhouse-migration.yaml
- helm/cosmo/charts/controlplane/templates/database-migration.yaml
- helm/cosmo/charts/controlplane/templates/deployment.yaml
- helm/cosmo/charts/controlplane/templates/organization-seed.yaml
- helm/cosmo/charts/controlplane/templates/secret.yaml
- helm/cosmo/charts/controlplane/values.yaml
- helm/cosmo/charts/graphqlmetrics/CHART.md
- helm/cosmo/charts/graphqlmetrics/templates/_helpers.tpl
- helm/cosmo/charts/graphqlmetrics/templates/deployment.yaml
- helm/cosmo/charts/graphqlmetrics/templates/secret.yaml
- helm/cosmo/charts/graphqlmetrics/values.yaml
- helm/cosmo/charts/otelcollector/CHART.md
- helm/cosmo/charts/otelcollector/templates/_helpers.tpl
- helm/cosmo/charts/otelcollector/templates/deployment.yaml
- helm/cosmo/charts/otelcollector/templates/secret.yaml
- helm/cosmo/charts/otelcollector/values.yaml
- helm/cosmo/charts/router/CHART.md
- helm/cosmo/charts/router/templates/_helpers.tpl
- helm/cosmo/charts/router/templates/deployment.yaml
- helm/cosmo/charts/router/templates/secret.yaml
- helm/cosmo/charts/router/values.yaml
Support existing secrets to:
*  avoid having sensitive credentials in Cosmo values.yaml.
* Support gitops workflow. ( external-secrets )
This PR closes #453
> feat(helm): support existing secrets

- router/core/flushwriter.go
We needed this in the past, but the responsibility is now in the engine. Obsolete code. Covered by existing tests.
> chore: remove obsolete mutex

- router/pkg/config/config.schema.json
This is a regression. The correct port is 3002
> fix: listen port in config

- cli/src/commands/subgraph/commands/check.ts
- connect/src/wg/cosmo/platform/v1/platform_pb.ts
- controlplane/src/core/bufservices/PlatformService.ts
- proto/wg/cosmo/platform/v1/platform.proto
Shows the link to studio page for the check in output.
> feat: show link to studio page on subgraph check

- controlplane/src/core/repositories/analytics/AnalyticsRequestViewRepository.ts
Client version was missing in the blacklist of grouped filters
> fix: omit invalid group filters

- controlplane/src/core/build-server.ts
- controlplane/src/core/services/Mailer.ts
Fix https://linear.app/wundergraph/issue/ENG-4915/controlplane-use-starttls-in-nodemailer
> feat: ensure TLS and test if mail client is ready

- controlplane/src/core/composition/composer.ts
> fix: subgraphs not found in composition details page

- pnpm-lock.yaml
- studio/.gitignore
- studio/next.config.mjs
- studio/package.json
- studio/src/components/schema/sdl-viewer-monaco.tsx
This will avoid loading monaco from the CDN and therefore makes our CSP policy more strict.
> fix: load monaco from public folder

- cli/src/commands/federated-graph/commands/create.ts
- cli/src/commands/federated-graph/commands/update.ts
- cli/src/commands/subgraph/commands/create.ts
- cli/src/commands/subgraph/commands/publish.ts
- cli/src/commands/subgraph/commands/update.ts
- connect/src/wg/cosmo/platform/v1/platform_pb.ts
- controlplane/src/core/bufservices/PlatformService.ts
- controlplane/src/core/repositories/FederatedGraphRepository.ts
- controlplane/src/core/repositories/SubgraphRepository.ts
- controlplane/src/core/services/AdmissionWebhookController.ts
- controlplane/test/subgraph.test.ts
- package.json
- pnpm-lock.yaml
- proto/wg/cosmo/platform/v1/platform.proto
- shared/src/utils/util.ts
- vitest.workspace.ts
- Allow to update admission url.
- Allow to unset several other flags with an empty value
- Cleanup flag handling.
- Remove unused header option from commands and proto in a backwards compatible way
- Add vitest.workspace.yaml for vscode debugging support (Upgrade the vscode plugin to the latest pre-release version)
> feat: allow to update admission url

- router-tests/authentication_test.go
- router/pkg/authentication/authentication.go
A lot of details about this problem is outlined in #645 .  This relatively trivial change fixes what appears to be a typo: the `scopes` keyword gleaned from the JWT token payload should be `scope` according to [RFC 8693](https://datatracker.ietf.org/doc/html/rfc8693#name-scope-scopes-claim).
Closes #645
> fix: change 'scopes' keyword to 'scope'

- studio/next.config.mjs
We need to find a way to enforce this without breaking the studio. A possible solution could be to proxy all requests through an intermediate server to enforce same domain policy. Setting the CSP header by reading the graphql url could be another way but requires a custom middleware. The proxy approach is easier.
> fix: remove connect-src CSP policy

- router-tests/prometheus_test.go
- router/core/engine_loader_hooks.go
Create a new metric per error code. This will also be exported correctly in prometheus.
> fix: create individual metrics per error code

- studio/src/components/federatedgraphs-cards.tsx
Lengthy urls were not being truncated.
> fix: url overflow in federated graph card

- cli/src/commands/subgraph/commands/introspect.ts
Allow to introspect subgraphs using standard introspection query.
> feat: enable raw introspection for subgraphs

- helm/cosmo/charts/router/README.md
- helm/cosmo/charts/router/templates/gateway.yaml
- helm/cosmo/charts/router/templates/istio-gateway.yaml
- helm/cosmo/charts/router/templates/istio-virtual-service.yaml
- helm/cosmo/charts/router/values.yaml
We use Istio and `istioGateway`/`VirtualService` rather than an ingress. We also don't have any plans to support the newer `ingressGateway`. This should provide the necessary resources to create the `istioGateway` and `VirtualService` (disabled by default).
> feat: add istioGateway and VirtualService to router helm chart

- helm/cosmo/charts/router/templates/istio-gateway.yaml
Fix the expansion of selectors in the istio-gateway template for the router helm chart, it was previously inlining it to the text representation of a Go map (my bad 😬 )
Supporting istio gateway for the router helm chart.
> fix: fix the expansion of selectors in the istio-gateway template for the router helm chart

- router/internal/wsproto/absinthe.go
Set the data with sjon rather than string concatenation which could result in unexpected behaviour.
> fix: set response properly as JSON data

- helm/cosmo/charts/router/README.md
- helm/cosmo/charts/router/values.yaml
Fix typo in default values and docs for the chart of router
> fix: fix default value for `extraEnvVars` in values for `router`

- connect/src/wg/cosmo/platform/v1/platform_pb.ts
- controlplane/src/core/bufservices/PlatformService.ts
- controlplane/src/core/repositories/FederatedGraphRepository.ts
- proto/wg/cosmo/platform/v1/platform.proto
- studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/index.tsx
The admission webhook URL was not being updated on passing empty string. Also shows it on the frontend
> fix: unset admission webhook using empty string

- studio/src/components/analytics/trace-details.tsx
> fix: display graphql operation and variables after truncation in trace detail view

- studio/src/components/app-provider.tsx
- studio/src/components/dashboard/NamespaceSelector.tsx
- studio/src/pages/[organizationSlug]/apikeys.tsx
- studio/src/pages/[organizationSlug]/audit-log.tsx
- studio/src/pages/[organizationSlug]/graphs.tsx
- studio/src/pages/[organizationSlug]/integrations.tsx
- studio/src/pages/[organizationSlug]/lint-policy.tsx
- studio/src/pages/[organizationSlug]/members.tsx
- studio/src/pages/[organizationSlug]/subgraphs.tsx
- studio/src/pages/[organizationSlug]/usages.tsx
- studio/src/pages/[organizationSlug]/webhooks.tsx
Refresh queries used to occuer even before the transport was set. Now we handle the reset in the app provider
> fix: reset queries on organization change

- helm/cosmo/charts/router/Chart.yaml
- helm/cosmo/charts/router/README.md
- helm/cosmo/charts/router/templates/config-map.yaml
- helm/cosmo/charts/router/values.yaml
Allows users of the Helm chart to use dynamic content for `.Values.commonConfiguration` string -- used in the Config Map.
```
commonConfiguration: |-
headers:
subgraphs:
someSubgraph:
{{- include "subgraph.headers" . | nindent 6 }}
```
Without this change, `.Values.commonConfiguration` is just a string, and the dynamic part does not get expanded.
> feat: use Helm tpl function on .Values.commonConfiguration

- otelcollector/otel-config.yaml
- router-tests/prometheus_test.go
- router-tests/telemetry_test.go
- router-tests/testenv/testenv.go
- router/core/engine_loader_hooks.go
- router/core/graphql_handler.go
- router/core/graphql_prehandler.go
- router/core/operation_metrics.go
- router/core/router.go
- router/core/router_metrics.go
- router/core/transport.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
- router/pkg/metric/config.go
- router/pkg/metric/meter.go
- router/pkg/trace/config.go
- router/pkg/trace/meter.go
- router/pkg/trace/middleware.go
- router/pkg/trace/middleware_test.go
Config
```yaml
cors:
allow_headers:
- "x-service"
telemetry:
resource_attributes:
- key: env
value: "prod"
attributes:
- key: service
default: "static"
value_from:
request_header: "x-service"
```
A resource attribute `env=prod` is added. Additionally, we add the attribute `service=static` to all metrics and spans unless the client has sent us a request header `x-service` with a set value.
> feat: allow to add custom OTEL attributes

- cli/.env.example
- cli/README.md
- cli/package.json
> chore(cli): add support for .env for development

- controlplane/src/core/repositories/FederatedGraphRepository.ts
The repository was not returning the secret to be passed to the controller.
> fix: empty admission webhook secret

- router-tests/file_upload_test.go
- router/cmd/instance.go
- router/core/graphql_prehandler.go
- router/core/router.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
Config to disable file uploads.
> feat: allow to disable file uploads

- keycloak/theme/src/main/resources/theme/cosmo/login/messages/messages_en.properties
- keycloak/theme/src/main/resources/theme/cosmo/login/resources/scss/login.scss
- keycloak/theme/src/main/resources/theme/cosmo/login/terms.ftl
Added "managed service" to match the exact legal name of the terms document in the consent modal.
> fix: update text snippet in messages_en.properties

- router/core/router.go
- router/internal/retrytransport/retry_transport.go
- router/pkg/config/config.go
- router/pkg/config/testdata/config_defaults.json
`ENGINE_MAX_CONCURRENT_RESOLVERS` has been chosen too low (32). The latency for medium and high load scenarios is increased a lot because max concurrency is implemented as a semaphore and blocks new requests. This PR increase the limit to `256`.
The settings has been validated with the following scenario.
400 VUs (Virtual users) over 30 seconds
- ENGINE_MAX_CONCURRENT_RESOLVERS: 256
- Artificial subgraph latency: 200ms
- Subgraph response size: 200KB
Memory consumption: ~300MB
Additionally, I've found out that we retry subgraph requests when the subgraph returns a different code than 2xx than 200 OK.
> fix: optimize max concurrency for medium, high load, don't retry on 2xx status codes

- controlplane/src/core/bufservices/PlatformService.ts
This does not fail the check process anyways. It reduces alerting in case the organization does not give permission to the GitHub app
> fix: log commit check failure as warning instead of error

- router-tests/response_compression_test.go
- router/core/graph_server.go
- router/core/router.go
- router/go.mod
- router/go.sum
This PR removes brotli compression support due to the very slow go implementation. Caddy the popular proxy solution made a similar [decision](https://github.com/caddyserver/caddy/issues/5194#issuecomment-1309845054). We will evaluate `zstd` as a possible alternative in the future. For now only gzip is supported in the router. I also migrated to https://github.com/klauspost/compress/tree/master/gzhttp which is an optimized compression middleware for gzip. In my test the implementation was 100% faster than the current gzip middleware from chi.
> fix: remove slow brotli compression and use optimized gzip middleware

- studio/src/components/dashboard/NamespaceSelector.tsx
- studio/src/components/ui/pagination.tsx
- studio/src/pages/[organizationSlug]/subgraphs.tsx
Changing page size when page number is greater than expected leads to empty results. Reset page number on page size change
> fix: broken pagination on page size change and subgraphs table with many items

- studio/src/components/schema/sdl-viewer.tsx
- studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/schema/index.tsx
> fix: get discussions only when targetId exists

- Makefile
fix full-demo-up hang or killed while Start the subgraphs and the router
✅ Closes: https://github.com/wundergraph/cosmo/issues/886
when I  run make full-demo-up,  It will hang or be killed  like this
It is  useless when  I change the Memory and CPU
I think the docker-compose use too much concurrency case any issues.
After I set the param of --parallel 3. It was work well
> fix:  make full-demo-up failure

- .release-please-manifest.json
- helm/cosmo/charts/router/CHANGELOG.md
- helm/cosmo/charts/router/Chart.yaml
- helm/cosmo/charts/router/README.md
This reverts commit 4f37aeaf9186b4118a2445a70b25606f830eca66.
> chore: revert router release from manifest 

- router/core/router.go
In the new version of the router, panic happens in the `persistedoperation` package when a SIGINT signal is received.
> fix: dont initialize persisted operation client when disabled

- router/core/header_rule_engine.go
- router/core/header_rule_engine_test.go
> fix: don't propagate client content negotiation headers with wildcard

- studio/src/components/feature-flag-details.tsx
> fix: disabled state of feature flag overview page

- controlplane/src/core/bufservices/PlatformService.ts
- controlplane/src/core/repositories/analytics/UsageRepository.ts
We have scoped schema usage always to a specific schema version. This resulted in the condition that after a schema change the usage has been reset. Types and fields can vary over versions but if we find usage it is valid across them.
> fix: dont scope schema usage to single schema version

- controlplane/src/core/bufservices/PlatformService.ts
> fix: delete federated graph audit in deleteNamespace

- studio/src/components/lint-policy/graph-pruning-config.tsx
> fix: graph pruning config ui for developer plan

- router-tests/header_propagation_test.go
- router-tests/header_set_test.go
- router/core/header_rule_engine.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/fixtures/full.yaml
- router/pkg/config/testdata/config_full.json
This PR expands our header propagation abilities, by allowing users to define a value to set on all request/response headers in the format: 
```
headers:
all: # Header rules for all subgraphs
request:
- op: "set"
name: "X-API-Key"
value: ${SECRET_FOR_SUBGRAPH}
```
The `set` operation works both for requests and responses, and it can be applied globally (to all requests on the router), or only on a specific subgraph.
> feat: implement set header

- controlplane/src/core/repositories/analytics/TraceRepository.ts
We need to opt in to the new achitecture in case the old one is being used.
> fix: set allow_experimental_analyzer = 1 for recursive query

- studio/src/components/lint-policy/graph-pruning-config.tsx
> fix: ui and default value of the graph pruning config

- router-tests/telemetry_test.go
- router-tests/testenv/testenv.go
- router/core/router.go
- router/go.mod
- router/go.sum
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/fixtures/full.yaml
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
- router/pkg/trace/config.go
- router/pkg/trace/propagation.go
This PR adds datadog trace propagation for users, which will set subgraph datadog headers (`x-datadog-trace-id`, `x-datadog-parent-id` and `x-datadog-sampling-priority`) based on the trace id/span id. 
In order to enable it, users can add 
```
telemetry: 
tracing: 
propagation:
datadog: true
```
to their configuration
> feat: enable datadog trace propagation

- router/core/websocket.go
This PR ensures that we don't modify the client request concurrently in multiple goroutines. We copy the request before registering the subscription. This change doesn't come with a big performance penalty because we were already forced to clone the headers. Furthermore, I moved URL parsing out of `executeSubscription` to do it only once in the websocket handler.
> fix(websocket): avoid data race on client request

- router/core/websocket.go
> chore: do not log client cancellation as errors

- router-tests/header_propagation_test.go
- router/core/header_rule_engine.go
Previous work (#1155 and #1218) added cache control policy control, and in the process, set a `Cache-Control` header on every response, even when it didn't have a value to set. This PR fixes that bug.
> fix: don't set empty cache control headers

- router/core/operation_processor.go
- router/core/operation_processor_test.go
> fix: introspection query detection

- helm/cosmo/charts/otelcollector/templates/deployment.yaml
Fixes the usage of the cm name as the volume name.
> fix: use volume name instead of config map name

- router-tests/websocket_test.go
- router/core/header_rule_engine.go
As seen in https://github.com/wundergraph/cosmo/issues/1149, when forwarding all the headers, the web socket connection doesn't work anymore. The change made with this pull request assures that the headers part of the web socket specification are not forwarded to the subgraph web socket connection.
> fix(websocket): prevent ws headers leaking to the subgraph ws connection (#1149)

- data_migrations/controlplane/1726744316_add_span_id_to_trace/files/migrate.go
The migration is not consistent with the overview in the readme “ We need to drop both the traces_mv materialized view and traces table, recreate and repopulate them. We do the repopulation in hourly batches.” as traces_mv is renamed to temp_traces_mv. This PR tweaks the code to make it consistent with the readme.
> chore(migration): data migration to maintain table name traces_mv

- controlplane/migrations/0102_common_tiger_shark.sql
- controlplane/migrations/meta/0102_snapshot.json
- controlplane/migrations/meta/_journal.json
- controlplane/src/db/schema.ts
Set it to null instead of doing nothing. Schema version is deleted on org deletion only so this is fine.
> fix: subgraph and schema version foreign key constraint

- controlplane/src/core/repositories/FederatedGraphRepository.ts
- controlplane/test/get-user-accessible-resources.test.ts
> fix: get user accessible resources of a developer

- admission-server/Dockerfile
- cdn-server/Dockerfile
- controlplane/Dockerfile
- studio/Dockerfile
=> ERROR [cdn builder  7/10] RUN pnpm install --filter=.  0.9s
------                                                          
> [cdn builder  7/10] RUN pnpm install --filter=./cdn-server/cdn --filter=./cdn-server --frozen-lockfile:                      
0.821  ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)                                   
0.821                                                           
0.821 Your pnpm version is incompatible with "/app".
0.821 
0.821 Expected version: 9
0.821 Got: 8.15.9
4 Dockerfiles have:
RUN npm install --global pnpm@8
Upgrading to:
RUN npm install --global pnpm@9
> chore(deps): sync pnpm version into Dockerfiles

- router-tests/automatic_persisted_queries_test.go
- router-tests/persisted_operations_over_get_test.go
- router-tests/persisted_operations_test.go
- router/core/errors.go
- router/core/graphql_prehandler.go
- router/core/operation_processor.go
- router/core/websocket.go
Previous PRs added APQ, and affected persisted operations. This PR makes two changes: 
* It closes #1179, ensuring that different client names can't access different users persisted operations
* It ensures that even when a persisted operation isn't found, it'll return 200, since it's a well formed GraphQL query
> fix(router): l2 cache uses client name in key, persisted operation not found returns 200

- router/core/router.go
It now uses load and store when checking if the server is shutdown, so it might introduce data race if calls the shutdown function at the same time. We can work around this by using CAS operation in atomic.
> chore(router): use automic's CAS to allow to shutdown the router concurrently

- router-tests/headers_test.go
- router/core/graph_server.go
- router/core/header_rule_engine.go
- router/core/request_context_fields.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/fixtures/full.yaml
- router/pkg/config/testdata/config_full.json
This, as similar work to #1203, enables users to propagate request headers from a subset of request context elements, such as operation name
```
headers:
all:
request:
-  operation: "set"
name: x-operation-name
value_from: # New
context_field: operation_name
```
> feat(router): enable setting request header from context

- router-tests/automatic_persisted_queries_test.go
- router/internal/persistedoperation/client.go
Previous efforts to add APQ in (#1346) failed to fully verify that APQ works even when persistent operations aren't set up, based on complexity in the test environment/router setup. This PR adds the required test, and fixes the null pointer bug that had existed prior.
> fix: ensure that apq alone (without persistent operations enabled) works

- router-tests/telemetry_test.go
- router-tests/testenv/testenv.go
- router/core/context.go
- router/core/graph_server.go
- router/pkg/metric/metric_store.go
- router/pkg/metric/router_runtime_metrics.go
This PR removes the runtime metric store from the graph mux because those metrics are shared across those like Go Memory stats and graph config uptime. Furthermore, we ensure that we work with the right base attributes when initiating a new metric store for the graph mux. Previously, we overridden the metric store from the graph server instead of creating a new one for mux. This has been fixed and verified with new integration tests.
> fix: move runtime metric store to graph server

- router-tests/structured_logging_test.go
- router/core/engine_loader_hooks.go
- router/core/header_rule_engine.go
- router/core/request_context_fields.go
- router/internal/requestlogger/subgraphlogger.go
- router/pkg/config/config.schema.json
With our work in adding access logs, we want to add a boolean field that users can watch to give them a simple indication if there was an error found in the request, whether a panic or a graphql error. It is also present in subgraph access logs, so it will exhibit which subgraph had the error
> feat(router): add request_error boolean field to access logs

- router-tests/normalization_cache_test.go
- router-tests/persisted_operations_test.go
- router-tests/testdata/cdn/organization/graph/operations/my-client/dc67510fb4289672bea757e862d6b00e83db5d3cbbcfb15260601b6f29bb2b8f.json
- router-tests/testenv/testdata/cdn/organization/graph/operations/my-client/724399f210ef3f16e6e5427a70bb9609ecea7297e99c3e9241d5912d04eabe60.json
- router/core/operation_processor.go
During improving the normalization logic, we didn't consider multi operation documents. 
Details: When a user hits the cache with a multi operation document, we only store the used operation in the cache. Therefore all places has to reference this document instead of using the index from the original operation document.
> fix: panic when normalizing multi operation documents

- router-tests/automatic_persisted_queries_test.go
- router/core/operation_processor.go
Only includes a failing tests. Expectation is that the operation is using the normalization cache.
> fix(APQ): set normalization cache hit stat correctly

- router-tests/automatic_persisted_queries_test.go
- router-tests/persisted_operations_over_get_test.go
- router-tests/persisted_operations_test.go
- router/core/errors.go
Apollo Client is reliant on the error _message_ rather than the error code.
This PR aims to facilitate seamless migration.
> chore: update persisted query not found error message

- router-tests/go.mod
- router-tests/go.sum
- router-tests/structured_logging_test.go
- router/core/engine_loader_hooks.go
- router/core/request_context_fields.go
- router/go.mod
- router/go.sum
- router/internal/requestlogger/subgraphlogger.go
- router/internal/requestlogger/subgraphlogger_test.go
There was a null pointer when consumers would encounter a subgraph with a null request (which can happen in error cases). This PR makes the code much more resilient, and adds tests to ensure that nil pointers are handled gracefully.
Resolves ENG-6173
> fix(router): ensure subgraph access logs handles null requests/errors

- .github/actions/build-push-image/action.yaml
- router-tests/authentication_test.go
- router-tests/modules/set_scopes_test.go
- router-tests/websocket_test.go
- router/cmd/instance.go
- router/pkg/authentication/jwks_token_decoder.go
It can't be always guaranteed that the JWK server is up and ready when the router starts. This is in particular true when the JWK is served from a sidecar. This PR allows the initial JWK refresh to fail. All errors are logged.
> feat: tolerate initial JWK error

- router-tests/block_operations_test.go
- router-tests/testenv/testenv.go
- router/cmd/main.go
- router/core/router.go
- router/internal/expr/expr.go
https://github.com/expr-lang/expr/issues/744
> fix(expressions): avoid exposing more methods as desired

- router/core/timout_transport_test.go
> fix: bump timeout in server to address responseheadertimeout flake

- cli/src/core/client/client.ts
- controlplane/src/core/build-server.ts
- controlplane/src/core/plugins/clickhouse.ts
- controlplane/src/core/routes.ts
> fix: update the timeouts for clickhouse and platform service

- docker-compose.yml
- router/.env.example
- router/demo.config.yaml
Since the last change that checks for edfs providers, the demo environment would not work by default. 
So we have to add the configuration and services needed by the router to work properly.
> fix: add edfs to the demo environment

- CONTRIBUTING.md
The `CONTRIBUTING.md` file currently says "we don't commit the `go.work` or `go.sum` files" but [you do](https://github.com/wundergraph/cosmo/blob/main/router/go.mod) and what the doc actually means to say is that you don't commit `go.work.sum` files. This wouldn't be an issue for anyone experienced with Go, but it could be misleading for first-time contributors or beginners to the language.
> docs(CONTRIBUTING): fixup minor mistake in CONTRIBUTING.md under Go workspace

- router-tests/graphql_over_get_test.go
- router-tests/graphql_over_http_test.go
- router/core/graph_server.go
`Mount()` appends a wildcard `*` to the graphql endpoint. We want to make sure we only hit the endpoint on the configured path. Wildcard url paths should not be taken into account and any other path than the configured paths should return 404.
> fix(router): remove wildcard from router graphql path

- router-tests/telemetry/telemetry_test.go
- router/pkg/metric/router_runtime_metrics.go
This PR change the server uptime metric from type counter to gauge. Counter was not correct because we are not interested in the aggregation but in the last value.
> fix: use gauge for server.uptime metric

- controlplane/src/core/repositories/CacheWarmerRepository.ts
- demo-router.fly.toml
This PR ensures that we consider the same date range for finding slow operation and fetching their content.
> fix(cache warmup): consider only po of the last 7 days

- demo/go.mod
- demo/go.sum
- router-tests/cache_warmup_test.go
- router-tests/go.mod
- router-tests/go.sum
- router-tests/integration_test.go
- router-tests/testenv/testdata/cache_warmup/simple/employee.gql
- router-tests/testenv/testdata/cdn/organization/graph/cache_warmup/operations.json
- router-tests/testenv/testdata/cdn/organization/graph/operations/my-client/e24399f210ef3f16e6e5427a70bb9609ecea7297e99c3e9241d5912d04eabe60.json
- router/core/cache_warmup.go
- router/core/context.go
- router/core/graphql_handler.go
- router/core/graphql_prehandler.go
- router/core/operation_planner.go
- router/core/operation_processor.go
- router/core/websocket.go
- router/go.mod
- router/go.sum
> feat: add variables remapping support

- router-tests/events/kafka_events_test.go
- router-tests/events/nats_events_test.go
- router/core/flushwriter.go
Users noted that mutlipart subscriptions weren't working with Apollo Client. This PR fixes two issues with the current multipart subscription, in order to fix it: 
*. It changes the main Content-Type header to `multipart/mixed; boundary=graphql`, to fit with the [W3 RFC](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) requirements (and the client's explicit parsing)
* It changes the line endings before the message to be `/r/n` instead of just `/n`, to fit with the RFC's explicit use of CRLF. 
```
const { ApolloClient, InMemoryCache, HttpLink} = require('@apollo/client');
const gql = require('graphql-tag');
// Define your subscription query
const SUBSCRIPTION_QUERY = `
subscription Test {
countFor(count: 5)
}
`;
// HTTP link for queries and mutations
const httpLink = new …
```
> fix(router): write proper line endings and header for multipart

- router-tests/testenv/testenv.go
- router/cmd/instance.go
- router/core/graph_server.go
- router/core/router.go
- router/internal/graphiql/playgroundhandler.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/fixtures/full.yaml
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
Previously, we were recomputing this template every time and loading it into memory every time you accessed the endpoint. This should fix that, and ensure we only compute it once.
> feat(router): optimize playground delivery, add concurrency_limit to config

- router-tests/structured_logging_test.go
- router-tests/testenv/testenv.go
- router/core/http_server.go
- router/core/router.go
Health checks are currently only available after the router has been initialized. The expected intended behavior is, that the health checks are available during setup and report liveness and correct readiness information.
`ready`
* during initialization -> false
* after initialization -> true
> fix(router): enable health checks during startup

- router/core/graph_server.go
- router/core/router.go
- router/pkg/execution_config/compatibility.go
- router/pkg/execution_config/compatibility_test.go
> feat: also add handshake for static execution configs

- controlplane/src/core/bufservices/federated-graph/updateFederatedGraph.ts
Federated graph update command used to shoot webhook on updating things that do not perform schema updates
> fix: webhooks shot when schema is unchanged

- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/testdata/config_defaults.json
Based on our observations in production and feedback from customers, we have concluded that the `ENGINE_MAX_CONCURRENT_RESOLVERS` value was set too low. Additionally, we have resolved a potential memory issue that we previously misattributed to this limit. A value that is too low can lead to increased latency in subgraph requests due to limited concurrency.
> fix: increase max concurrent resolvers

- router/cmd/main.go
- router/core/graph_server.go
- router/internal/jwt/claims.go
> fix: error when graph token is not set when cache warmup is enabled

- router/core/graph_server.go
- router/core/router.go
- router/core/subgraph_transport_test.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
- **feat(router): add configurable connection limits for each subgraph**
- **test: update snapshots**
Users want to configure connection limits for the router, including per-subgraph values. 
Example config utilizing this feature:
```yaml
traffic_shaping:
all:
max_idle_conns: 1024
max_conns_per_host: 100
max_idle_conns_per_host: 20
subgraphs:
employees:
max_idle_conns: 4096
max_conns_per_host: 400
max_idle_conns_per_host: 80
```
> feat(router): add configurable connection limits for each subgraph

- Makefile
- demo/go.mod
- demo/go.sum
- router-tests/go.mod
- router-tests/go.sum
- router/go.mod
- router/go.sum
> fix: extracting arguments input objects with optional variables

- router-tests/apollo_compatibility_test.go
- router-tests/go.mod
- router-tests/go.sum
- router/cmd/instance.go
- router/core/graph_server.go
- router/core/operation_processor.go
- router/core/router.go
- router/go.mod
- router/go.sum
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
- Updates `graphql-go-tools` to [v2.0.0-rc.154](https://github.com/wundergraph/graphql-go-tools/releases/tag/v2.0.0-rc.154), incorporating Apollo Router compatibility options
- Adds a new config section `apollo_router_compatability_flags` that includes the option `replace_invalid_var_errors` which enables Cosmo/Router to return Apollo Router-like errors instead of Apollo Gateway-like or standard.
- Adds a new E2E test for this behavior
- [New docs](https://app.gitbook.com/o/AGsPMiPE3xradDAKeJYL/s/f2zpPO8tcaY6tJoaEebc/~/changes/SM1MfIihDRSR5SsqEeMG/router/configuration)
```yaml
version: "1"
apollo_router_compatibility_flags:
replace_invalid_var_errors:
enabled: true
```
> feat: apollo router compatibility options + router-like invalid vars

- demo/go.mod
- demo/go.sum
- router-tests/apollo_compatibility_test.go
- router-tests/go.mod
- router-tests/go.sum
- router/core/executor.go
- router/core/graph_server.go
- router/go.mod
- router/go.sum
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
- Adds config option `/apollo_router_compatibility_flags/subrequest_http_error/enabled` which enables Apollo Router like behaviour when subgraphs return non-2XX http status.
- Bumps `graphql-go-tools` to (v2.0.0-rc.156)[https://github.com/wundergraph/graphql-go-tools/releases/tag/v2.0.0-rc.156] to support this functionality
* apollo-router-like non-ok http status errors ([#1072](https://github.com/wundergraph/graphql-go-tools/issues/1072)) ([e685c29](https://github.com/wundergraph/graphql-go-tools/commit/e685c29331c0d1879ff8e099d4441047fbddf054))
> feat(engine): apollo router compatible non-2XX response errors

- router-tests/modules/custom-set-auth-scopes/module.go
- router-tests/modules/custom-set-scopes/module.go
- router-tests/modules/custom-trace-propagator/module.go
- router-tests/modules/custom_trace_propagator_test.go
- router-tests/modules/module_test.go
- router-tests/modules/set_authentication_scopes_test.go
- router-tests/modules/set_scopes_test.go
- router-tests/modules/verify-scopes/module.go
- router/cmd/custom/module/module.go
- router/core/context.go
- router/pkg/authentication/authentication.go
Some customers need to set the scopes on a request without authentication. This is not possible right now because you need the authentication object to be initialized to set the scopes inside of it.
In this PR I added the method `SetAuthenticationScopes` to the context to make it possible to set scopes on a request with or without authentication.
I had to remove the registration of the test custom modules to avoid interference between them.
> feat: set the scopes on request without authentication

- controlplane/src/core/webhooks/OrganizationWebhookService.ts
This PR adds the missing changes with the change type "CHANGED" in the Slack notification.
> fix: include changedTypes in the list of changes displayed in the slack notification

- router-tests/headers_test.go
- router-tests/testenv/testenv.go
- router/core/graph_server.go
- router/internal/middleware/cookie_filter.go
- router/internal/middleware/cookie_filter_test.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/fixtures/full.yaml
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
- Adds config option `/headers/cookie_whitelist: []string` that represents a list of allowed cookie "keys" to be propagated by the router
- It achieves this by stripping unwanted headers off the request using standard HTTP middleware on the graph server
- An empty or unspecified value means allow all, users should just disable `Cookie` header propagation if they don't want any cookies
- This option will have little to no effect if `Cookie` is not a propagated header.
- `Cookie` being a `set` header should not be affected by this at all
> feat(router): cookie header whitelist

- demo/go.mod
- demo/go.sum
- router-tests/go.mod
- router-tests/go.sum
- router/core/executor.go
- router/core/router.go
- router/go.mod
- router/go.sum
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
This PR bumps the engine with the subscription handling refactor https://github.com/wundergraph/graphql-go-tools/pull/1076
It exposes the `subscription_fetch_timeout` property to configure the maximum time a subscription fetch can take before it is considered timed out.
> feat(subscription): mutex free subscription implementation

- cli/src/commands/graph/federated-graph/commands/fetch.ts
- cli/src/commands/graph/federated-graph/utils.ts
This PR adds the client schema of the federated graph in the output of `wgc federated-graph fetch` command.
> feat: include client schema in the output of federated-graph fetch command

- .github/workflows/cli-binary-release.yaml
- Gzips the built binaries for artifact size optimization
- Added `experimental` to released filenames
> ci: optimize bun binaries and put experimental in the name

- .github/workflows/router-ci.yaml
- router-tests/testenv/testenv.go
- patch for seemingly load related integration test failures perhaps as a result of all the new CLI tests
- runs kafka as github CI service instead of container for the time being
- kafka service configuration is transplanted from the `docker-compose.yml` file
I intend to find a nicer solution soon.
> test: run kafka as github CI service instead of container

- router-tests/prometheus_test.go
- router-tests/testenv/testenv.go
- router/core/router.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/config_events_kafka_test.go
- router/pkg/config/config_events_nats_test.go
- router/pkg/config/config_test.go
- router/pkg/config/fixtures/full.yaml
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
- router/pkg/metric/config.go
- router/pkg/metric/meter.go
- **test: improve config tests with parallel, fix testify parameter ordering**
- **feat: config to disable otel scope info in prometheus metrics**
> feat: option to remove scopeinfo from prometheus metrics

- router-tests/events/nats_events_test.go
- router/core/flushwriter.go
This PR adds the required carriage returns to make multipart subscriptions compatible with apollo kotlin client. This is as apollo kotlin requires a preceeding carraige return on newlines when partitioning parts for multipart responses.
> fix: make multipart subscriptions compatible with client

- router/cmd/plan_generator.go
- router/core/plan_generator.go
- router/pkg/plan_generator/plan_generator.go
A customer is having issues with how much memory the query planner is using. After some debugging we found two things:
- the customer was deploying the query planner in a container, and the query planner was instead using the memory and cpu limits from the host
- the PlanGenerator was creating a new plan.Configuration and ast.Document for each go routine
This PR is acting on this two issues:
- using `go.uber.org/automaxprocs/maxprocs` and `github.com/KimMachineGun/automemlimit/memlimit` to recognize when running inside a container and set the right limits
- refactoring the PlanGenerator so that it can be instantiate only one time, and then each operation can get its own planner.
Testing with a big configuration (9MB), a concurrency of 20 and 643 queries, with the query-plan deployed with …
> feat(plan-generator): improve memory and cpu usage

- .github/scripts/setup-keycloak.sh
- .github/workflows/controlplane-ci.yaml
- controlplane/src/core/bufservices/user/updateOrgMemberRole.ts
- controlplane/src/core/services/Keycloak.ts
- controlplane/test/test-util.ts
When updating member roles the operation could take anywhere from a few seconds to over a minute (eventually failing).
Both operations were executed with 7400 organizations.
Before:
After:
The `organizations` are created as groups inside `Keycloak` and the roles are subgroups of the organizations.
To find the identifier of the role in `Keycloak` we were searching by the role name, for example `admin`, this causes `Keycloak` to return all the organizations as the `admin` role should exist in all of them. This issue scales with the amount of organizations created in `Keycloak`.
Something that added to the issue is that we were performing this operation 3 times in a row to load the relevant organization roles.
The solution is to use the organization identifier (`kcGroupId`) to list the …
> fix: improve performance when updating member role

- cli/src/commands/subgraph/commands/check.ts
When attempting a schema check for a subgraph, if the schema file is not found, it incorrectly reports that a readme file has not been found.
> fix(cli): typo in schema check

- router-tests/error_handling_test.go
- router/core/errors.go
- router/core/flushwriter.go
- router/core/flushwriter_test.go
Some clients have various requirements for parsing multipart (for example one client needs the specification in the content-type returned, if not it wont parse multipart). To avoid all of these complexities we will default to returning json for non-subscription operations WHEN the `accept` header has `application/json` in the value, so if `application/json` is even the 10th entry we will prefer it.
This also mimics the behaviour of a different product.
> fix: prefer json as a content type for non subscriptions

- controlplane/src/core/repositories/analytics/SubgraphMetricsRepository.ts
A bug was introduced where the `p90` and `p99` latencies were calculated incorrectly when looking at an specific subgraph analytics. The main graph analytics was unaffected by this.
> fix: fix incorrect calculation of the `p90` and `p99` subgraph metrics

- router-tests/go.mod
- router-tests/go.sum
- router/go.mod
- router/go.sum
* catch an error on provides with fragments ([#1115](https://github.com/wundergraph/graphql-go-tools/issues/1115)) ([f4bb0af](https://github.com/wundergraph/graphql-go-tools/commit/f4bb0afa4b0124eff279635f7a0dc7d65d2e8554))
> fix: catch an error on provides with fragments

- router-tests/structured_logging_test.go
- router/core/access_log_field_handler_test.go
- router/core/attribute_expressions.go
- router/core/attribute_expressions_test.go
- router/core/graph_server.go
- router/core/graphql_prehandler.go
- router/core/operation_blocker.go
- router/core/ratelimiter.go
- router/core/ratelimiter_test.go
- router/internal/expr/expr.go
- router/internal/expr/expr_manager.go
- router/internal/expr/expr_manager_test.go
- router/internal/expr/resolvers.go
- router/internal/expr/use_body.go
- router/internal/expr/use_body_test.go
- router/internal/expr/visitor_group.go
- router/internal/requestlogger/access_log_expression.go
- router/internal/requestlogger/access_log_expression_test.go
We want to add the request raw body to the expression context. This will allow users to use the body as the basis for expressions throughout the router.
> feat: add request body to expression context

- cli/src/commands/graph/common/fetch-schema.ts
- cli/test/fetch-schema.test.ts
By default, the `monograph fetch-schema` and `federated-graph fetch-schema` output the router schema SDL. This PR introduces a way to output the client schema SDL instead.
> feat: implement `--client-schema` flag

- studio/src/components/analytics/metrics.tsx
- studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/analytics/index.tsx
- studio/src/pages/[organizationSlug]/[namespace]/subgraph/[subgraphSlug]/analytics/index.tsx
As a user, when I hover over any analytics widget, should see the same highlited timestamp for other widgets in the page.
https://github.com/user-attachments/assets/b918625d-2e38-41b3-a135-0f8b9ecc3d77
> feat: synchronize hovering all graphs in analytics pages

- cli/src/commands/mcp/tools/subgraph-verify-schema-changes.ts
This pull request includes significant changes to the `registerSubgraphVerifySchemaChangesTool` function in the `cli/src/commands/mcp/tools/subgraph-verify-schema-changes.ts` file. The changes focus on modifying the schema parameter handling and improving the formatting of the check results.
* The `schema` parameter is now mandatory instead of optional, ensuring that the new schema SDL is always provided.
* Simplified the conversion of the `schema` parameter to a `Uint8Array`.
* Removed the `formatResults` function that manually formatted the check results into a readable string.
* Replaced the manual formatting with a JSON stringified response that includes additional check success status information.
* Introduced the `isCheckSuccessful` function to determine the overall success of the …
> fix: improve subgraph change verification

- router-tests/events/kafka_events_test.go
- router/core/graph_server.go
- router/core/http_server.go
This PR fixes an issue with the graceful shutdown. 
The write lock actually caused the existing read locks to be blocked. During the server shutdown we attempt to close idle connections but the connections have never been served and were waiting for the handler function. The handler function is blocked by read locks, which were blocked by the write lock.
As we set the write lock before shutting down the server, we prevented any inflight requests from completing. The only reason for the write lock is to set the `graphServer` and `handler` to nil.
By moving the write lock further down, we can ensure that any inflight requests are being processed before shutting down the http server without blocking the handler.
Also unrelated improvement:
`operationHashCache` was not closed yet
> fix(router): graceful shutdown blocked by in-flight requests due to lock

- helm/cosmo/Chart.yaml
- helm/cosmo/README.md
- helm/cosmo/charts/controlplane/Chart.yaml
- helm/cosmo/charts/controlplane/README.md
- helm/cosmo/charts/router/Chart.yaml
- helm/cosmo/charts/router/README.md
- helm/cosmo/charts/studio/Chart.yaml
- helm/cosmo/charts/studio/README.md
This pull request includes version updates for the `controlplane`, `router`, and `studio` charts in the Helm configuration. The most important changes are the updates to the `appVersion` in both the `Chart.yaml` and `README.md` files for each of these components.
Version updates:
* [`helm/cosmo/charts/controlplane/Chart.yaml`](diffhunk://#diff-76a32f140f02dd1eeba476535b6871995190bc4caa331ae9a29ee28cbfc8c097L23-R23): Updated `appVersion` from "0.125.0" to "0.133.1".
* [`helm/cosmo/charts/controlplane/README.md`](diffhunk://#diff-dea24c7628e27e41ba25f258ed35481700257bf5e48a2ae8bca0401836886659L3-R3): Updated `AppVersion` badge from "0.125.0" to "0.133.1".
* [`helm/cosmo/charts/router/Chart.yaml`](diffhunk://#diff-48692f19ca9f4f61361e95b52c5eb8f50336046ac4c88b821d0637c9ebd09464L24-R24): …
> chore: bump helm chart versions

- helm/cosmo/Chart.yaml
- helm/cosmo/README.md
This pull request includes a version update for the Helm chart of the WunderGraph Cosmo application.
Version update:
* [`helm/cosmo/Chart.yaml`](diffhunk://#diff-92340eb5c6356f50976b456e0fb8c1d04593d5ca11d5f41006f87e878a0be96fL19-R19): Updated the chart version from '0.14.0' to '0.14.1'.
* [`helm/cosmo/README.md`](diffhunk://#diff-34aedcd17a51f815addb1acf5b680da11758d35bd8cf11f17c3040b1322a34c5L5-R5): Updated the version badge to reflect the new version '0.14.1'.
> fix: bump umbrella version

- controlplane/src/core/controllers/auth.ts
This pull request includes a small but important change to the `controlplane/src/core/controllers/auth.ts` file. The change ensures that the `redirectURL` is validated to start with the `webBaseUrl` before redirecting. If it does not, the code now redirects to the `webBaseUrl` to prevent potential security issues.
* Added validation to check if `redirectURL` starts with `opts.webBaseUrl` before redirecting. If not, it redirects to `opts.webBaseUrl`. (`controlplane/src/core/controllers/auth.ts`)
> fix: only redirect to cosmo urls

- controlplane/test/check-subgraph-schema.test.ts
A test to ensure a schema check does not error out if one of the subgraphs has an empty sdl
> test: schema check when one of many subgraphs is empty

- studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/compositions/[compositionId]/feature-flag/[featureFlagCompositionId]/index.tsx
- studio/src/pages/[organizationSlug]/[namespace]/graph/[slug]/feature-flags/[featureFlagSlug]/index.tsx
- studio/src/pages/[organizationSlug]/feature-flags/[featureFlagSlug]/index.tsx
An issue was found caused by importing the `Button` component from the `react-day-picker` package instead of the components library which caused the error `useDayPicker must be used within a DayPickerProvider` to be raised.
> fix: solve issue caused by improper use of `useDayPicker`

- controlplane/migrations/0119_true_reptil.sql
- controlplane/migrations/meta/0119_snapshot.json
- controlplane/migrations/meta/_journal.json
- controlplane/src/core/bufservices/proposal/createProposal.ts
- controlplane/src/core/bufservices/proposal/updateProposal.ts
- controlplane/src/core/bufservices/subgraph/deleteFederatedSubgraph.ts
- controlplane/src/core/bufservices/subgraph/publishFederatedSubgraph.ts
- controlplane/src/core/repositories/OrganizationRepository.ts
- controlplane/src/core/repositories/ProposalRepository.ts
- controlplane/src/core/webhooks/OrganizationWebhookService.ts
- controlplane/src/db/schema.ts
- controlplane/test/integrations.test.ts
- controlplane/test/webhooks.test.ts
- studio/src/components/notifications/components.tsx
- studio/src/pages/[organizationSlug]/webhooks.tsx
- Introduced a new SQL migration to create the `webhook_proposal_state_update` table with necessary constraints and indexes.
- Updated the `OrganizationRepository` to handle proposal state updates and store relevant data in the new table.
- Enhanced the `OrganizationWebhookService` to include the new event type for proposal state updates.
- Modified the notification components to support displaying proposal state update events.
- Adjusted the proposal creation and update processes to trigger state updates when necessary.
> feat: add webhook proposal state update functionality

- router-tests/go.mod
- router-tests/go.sum
- router-tests/header_propagation_test.go
- router/core/errors.go
- router/core/graphql_handler.go
- router/go.mod
- router/go.sum
Current behaviour does not treat unreachable subgraph, or other router-sourced errors as `no-cache`, we now explicitly set `Cache-Control` to `no-cache` 
* remove intermediate buffer from ResolveGraphQLResponse ([#1137](https://github.com/wundergraph/graphql-go-tools/issues/1137)) ([9f25e6f](https://github.com/wundergraph/graphql-go-tools/commit/9f25e6fccd15fa0a847d453ebd05276c2b250721))
> fix: set cache-control to `no-store` when errors are present, engine v2.0.0-rc.175

- router-tests/telemetry/telemetry_test.go
Right now the telemetry tests use array index for tests. Thus if the array element order changes due to a change in the code the tests will fail. This tests fixes this by making the telemetry tests get the required array (scope metric) element by name, instead of relying on the array index then.
This is opened as a separate PR, before the router gauge PR.
> fix: refactor telemetry tests

- studio/next.config.mjs
Using the HTTP response headers X-Content-Type-Options: nosniff and X-Frame-Options: deny is a widely recommended security best practice to protect web applications against MIME-sniffing and Clickjacking scenarios "iframe".
> fix: protect against mime type sniffing and clickjacking

- router/go.mod
- router/go.sum
This pull request updates the version of a dependency in the `router/go.mod` file. The change upgrades `github.com/wundergraph/graphql-go-tools/v2` from version `v2.0.0-rc.176` to `v2.0.0-rc.177`.
> fix: update go tools

- router-tests/go.mod
- router-tests/go.sum
- router-tests/introspection_test.go
- router-tests/testdata/introspection/base-graph-schema.json
- router-tests/testdata/introspection/feature-graph-schema.json
- router/go.mod
- router/go.sum
Add support of deprecated directive arguments, field arguments and input object arguments
Updates engine to [v2.0.0-rc.178](https://github.com/wundergraph/graphql-go-tools/releases/tag/v2.0.0-rc.178)
* add deprecated arguments support to introspection ([#1142](https://github.com/wundergraph/graphql-go-tools/issues/1142)) ([1ac2908](https://github.com/wundergraph/graphql-go-tools/commit/1ac2908ec5ab5cfb5aed17c1fee127aef098c7fc))
> feat: add support for deprecated arguments in introspection

- router-tests/cache_warmup_test.go
- router-tests/persisted_operations_test.go
- router-tests/testenv/testdata/cdn/organization/graph/operations/my-client/9015ddfadd802bb378a14e48cea51e9bf9a07c7f8a71d85c56d7b104fea84937.json
- router/core/operation_processor.go
- router/core/router.go
- router/internal/persistedoperation/operationstorage/fs/client.go
closes #1824 
Fixes a problem when safelisted persisted operation was loaded via query body, but was not properly marked as persited, which was having 2 consequences:
- persisted operation cache was not populating
- we were not using persisted operation body, after consequent calls via hash and body
Bonus:
- Adds file storage provider support to persisted operations
> fix: call safelisted operation after persisted one; feat: add file storage for persisted operations

- studio/src/lib/track.ts
Posthog has conflicting docs with identify call. For now we can get the posthog id and pass it to identify.
> fix: posthog distinct id for identify

- controlplane/src/core/bufservices/federated-graph/checkFederatedGraph.ts
- controlplane/test/check-federated-graph.test.ts
This PR fixes checkFederatedGraph to handle subgraphs without schemas during composition.
> fix: checkFederatedGraph by filtering out subgraphs without schemas for composition

- router-tests/config_hot_reload_test.go
This PR retries a config poller test that may be flaky.
> fix: rename test to flaky so it can be retried

- router-tests/lifecycle/supervisor_test.go
- router/core/graph_server.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/fixtures/full.yaml
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
The enabled option doesn't really make sense in this case. Currently we have a default hello-world plugin and this would cause it not to load when this config is disabled
> chore: remove enabled plugin config

- router/core/executor.go
- router/core/factoryresolver.go
- router/core/graph_server.go
- router/core/plan_generator.go
- router/pkg/config/config.go
- router/pkg/config/config.schema.json
- router/pkg/config/fixtures/full.yaml
- router/pkg/config/testdata/config_defaults.json
- router/pkg/config/testdata/config_full.json
We recently removed the enabled flag for the plugins as it didn't make sense the way it was implemented. Instead of enabling only the configuration options this PR adds an implementation to handle enabling of plugins in general.
Enabled now will make sure that no plugins are loaded when enabled is set to false.
> feat: add proper enabled config for plugins

- router-tests/telemetry/connection_metrics_test.go
- router/internal/traceclient/traceclient.go
- router/pkg/metric/connection_measurements.go
This PR switches from float seconds to ms so that we can reuse the same ms buckets. 
Note that in a local / non stressed environment, acquiring cached connections will be less than 1 ms, meaning that all the entries in the bucket will be increased by 1.
> fix: use ms measurements instead of float seconds for conn_acquire_time

- controlplane/src/core/repositories/FeatureFlagRepository.ts
- controlplane/src/core/repositories/NamespaceRepository.ts
- controlplane/src/core/repositories/SubgraphRepository.ts
- controlplane/src/core/services/RBACEvaluator.ts
Restore legacy read access to API keys when no group have been assigned to them.
> feat: fallback to legacy read access check for api keys

- helm/cosmo/charts/router/Chart.yaml
- helm/cosmo/charts/router/README.md
- helm/cosmo/charts/router/templates/deployment.yaml
This pull request includes updates to the Helm chart for the `router` component, focusing on versioning and YAML rendering improvements. The most important changes include incrementing the chart version and ensuring proper YAML formatting for additional volumes and volume mounts.
* [`helm/cosmo/charts/router/Chart.yaml`](diffhunk://#diff-48692f19ca9f4f61361e95b52c5eb8f50336046ac4c88b821d0637c9ebd09464L18-R18): Incremented the chart version from `0.10.1` to `0.10.2` to reflect changes made in the chart templates.
* [`helm/cosmo/charts/router/templates/deployment.yaml`](diffhunk://#diff-e6aabf4b8e03c68dedebad1cf7d36b587209346ec3aba11cba92d927bd8ace5dL206-R206): Updated the rendering of `extraVolumeMounts` to use `toYaml` for proper YAML formatting.
* …
> fix: extra volume mounts not rendered properly

- controlplane/src/core/bufservices/cache-warmer/pushCacheWarmerOperation.ts
- controlplane/src/core/bufservices/contract/updateContract.ts
- controlplane/src/core/bufservices/federated-graph/checkFederatedGraph.ts
- controlplane/src/core/bufservices/federated-graph/generateRouterToken.ts
- controlplane/src/core/bufservices/monograph/publishMonograph.ts
- controlplane/src/core/bufservices/monograph/updateMonograph.ts
- controlplane/src/core/bufservices/proposal/createProposal.ts
- controlplane/src/core/bufservices/proposal/updateProposal.ts
- controlplane/src/core/bufservices/subgraph/checkSubgraphSchema.ts
- controlplane/src/core/errors/errors.ts
- controlplane/src/core/services/RBACEvaluator.ts
- controlplane/test/check-subgraph-schema.test.ts
- controlplane/test/graph-pruning.test.ts
- controlplane/test/oidc-provider.test.ts
- controlplane/test/organization-groups.test.ts
- controlplane/test/rbac-evaluator.test.ts
Due to an oversight in the new RBAC implementation, we were not allowing legacy API keys to perform checks.
> feat: restore legacy support for check endpoints

- helm/cosmo/charts/router/Chart.yaml
- helm/cosmo/charts/router/README.md
- helm/cosmo/charts/router/templates/config-map.yaml
- helm/cosmo/charts/router/templates/deployment.yaml
- helm/cosmo/charts/router/templates/service.yaml
- helm/cosmo/charts/router/values.yaml
This pull request introduces a new feature to enable and configure an MCP server in the Helm chart for the WunderGraph Cosmo Router. It also includes updates to the chart version and documentation. 
* Adds mcp config options to the router helm chart
* Bumped chart version to 0.11.0
* Improves formatting of rendered yaml
> feat: support mcp in router helm chart

- helm/cosmo/charts/router/Chart.yaml
- helm/cosmo/charts/router/README.md
- helm/cosmo/charts/router/templates/config-map.yaml
- helm/cosmo/charts/router/values.yaml
When config gets large it's easier to manage it as an external file:
- lint with external tools
- get proper syntax support in editors
- share the same config across multiple instances of a router
Fixes: https://github.com/wundergraph/cosmo/issues/1962
> feat(helm): allow using config of a router from a file

- router-tests/websocket_test.go
- router/core/websocket.go
- router/internal/wsproto/absinthe.go
- router/internal/wsproto/graphql_ws.go
- router/internal/wsproto/proto.go
- router/internal/wsproto/subscriptions_transport_ws.go
We had a subtle timing dependent bug due to closing connections from within ws proto handlers, these are closed by netpoll under better conditions when left alone. 
This fixes a bug where it could almost seem as though we had partial reconnect support because the subscription was not entirely removed before clients reconnected, and also fixes an issue where the engine stats were leaking connections.
After this change, when a subgraph goes down triggering a close event, clients are fully disconnected and state is cleared.
Also some unrelated "modernize" linter fixes, just leaving the place in better condition than I found it.
> fix: let netpoll handle closing websockets

- router/pkg/config/config_test.go
There is a line which causes unexpected failures because the asserted error would return "file, storage" for the most part but occasionally would switch the order of the attributes. The hypothesis is this is due to how merging works as it uses maps whose order is not guaranteed in go.
Either way as this line is asserted separately for file and storage we skip it.
> fix: cleanup flaky line for router build test

- cli/package.json
- cli/src/index.ts
- pnpm-lock.yaml
The previous release had a bug that forced some logging to the terminal, breaking the wgc --json output for chaining with jq and other tools.
> fix(cli): make .env loading silent to prevent invalid json output
